"use client";

import { useState } from "react";
import { money } from "@/lib/crm-client";

const STAGE_LABEL={booking:"Giữ chỗ",deposit:"Đặt cọc",negotiation:"Thương lượng",contract:"Hợp đồng",completed:"Hoàn tất",cancelled:"Hủy"};
const PLOT_STATUS={available:"Mở bán",hold:"Giữ chỗ",deposit:"Đặt cọc",sold:"Đã bán",locked:"Khóa"};
const vietnamDate=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Ho_Chi_Minh",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());

export function CemeteryDealsModule({data,permissions,coreMutate,cemeteryAction,finance={}}){
  const deals=data.deals||[];
  const role=data.user.role;
  const isSale=role==="sale";
  const[modal,setModal]=useState(null),[plot,setPlot]=useState(null),[checking,setChecking]=useState(false),[error,setError]=useState(""),[deleteTarget,setDeleteTarget]=useState(null);
  function financeLinks(d){const contracts=(finance.contracts||[]).filter(x=>x.deal_id===d.id).length;const payments=(finance.payments||[]).filter(x=>x.deal_id===d.id).length;const commissions=(finance.commissions||[]).filter(x=>x.deal_id===d.id).length;return{contracts,payments,commissions,total:contracts+payments+commissions}}
  function canRemoveDeal(d){return Boolean(d)&&["booking","cancelled"].includes(d.stage)&&financeLinks(d).total===0}
  function saleLocked(d){return isSale&&d?.mode==="edit"&&!['booking','cancelled'].includes(d.stage)}
  function stageOptions(){if(!isSale)return Object.entries(STAGE_LABEL);if(modal?.mode==="add")return [["booking",STAGE_LABEL.booking]];if(saleLocked(modal))return [[modal.stage,STAGE_LABEL[modal.stage]||modal.stage]];return [["booking",STAGE_LABEL.booking],["cancelled",STAGE_LABEL.cancelled]]}
  function openAdd(){const first=data.leads?.[0];setPlot(null);setError("");setModal({mode:"add",lead_id:first?.id||"",plot_code:"",value:"",commission:"0",notes:"",stage:"booking"})}
  function openEdit(d){setPlot(null);setError("");setModal({mode:"edit",...d,value:d.value??0,commission:d.commission??0,notes:d.notes||"",stage:d.stage||"booking"})}
  async function checkPlot(){const code=String(modal?.plot_code||"").trim();if(!code)return;setChecking(true);setError("");try{const out=await cemeteryAction("detail",{code});if(!out.plot)throw new Error("Không tìm thấy mã mộ phần");setPlot(out.plot);setModal(m=>({...m,value:Number(m.value||0)>0?m.value:Number(out.plot.price_before_vat||0)}))}catch(e){setPlot(null);setError(e.message)}finally{setChecking(false)}}
  async function submit(e){e.preventDefault();setError("");try{if(isSale&&modal.mode==="add"&&modal.stage!=="booking")throw new Error("Sale chỉ được tạo giao dịch ở giai đoạn Giữ chỗ.");if(saleLocked(modal))throw new Error("Giao dịch đã qua bước Giữ chỗ. Sale chỉ được theo dõi; các bước cọc, hợp đồng và hoàn tất phải đi qua quy trình Tài chính.");if(isSale&&modal.mode==="edit"&&!['booking','cancelled'].includes(modal.stage))throw new Error("Sale chỉ được giữ chỗ hoặc hủy giữ chỗ của mình.");if(modal.mode==="add"){if(!plot)throw new Error("Vui lòng kiểm tra mã mộ trước khi tạo giao dịch");if(plot.sales_status!=="available")throw new Error(`Mộ ${plot.code} hiện đang ở trạng thái ${PLOT_STATUS[plot.sales_status]||plot.source_status||plot.sales_status}, không thể giữ chỗ mới.`);const lead=(data.leads||[]).find(l=>l.id===modal.lead_id);if(!lead)throw new Error("Vui lòng chọn khách hàng");await coreMutate("save_deal",{lead_id:lead.id,property_id:plot.id,value:modal.value||plot.price_before_vat||0,commission:modal.commission||0,stage:modal.stage||"booking",owner_id:lead.owner_id||data.user.id,deal_date:vietnamDate(),notes:modal.notes||""})}else{await coreMutate("save_deal",{...modal,value:modal.value||0,commission:modal.commission||0,notes:modal.notes||"",owner_id:modal.owner_id||data.user.id,deal_date:modal.deal_date||vietnamDate()})}setModal(null);setPlot(null)}catch(e2){setError(e2.message)}}
  async function deleteDeal(){if(!deleteTarget)return;if(!canRemoveDeal(deleteTarget)){setError("Giao dịch đã phát sinh cọc, hợp đồng, thanh toán hoặc hoa hồng. Hãy chuyển giai đoạn sang Hủy để giữ lịch sử thay vì xóa.");setDeleteTarget(null);return}setError("");try{await coreMutate("delete_deal",{id:deleteTarget.id});setDeleteTarget(null)}catch(e){setError(e?.message||"Không thể xóa giao dịch.")}}
  return <div className="suite-page"><div className="suite-page-head"><div><span className="eyebrow">THIÊN PHÚC VĨNH HẰNG VIÊN</span><h1>Giữ chỗ · Đặt cọc · Giao dịch</h1><p>Mỗi giao dịch gắn trực tiếp với một mã mộ phần để tránh bán trùng.</p></div>{permissions.deals_create&&<button className="suite-btn primary" onClick={openAdd}>+ Tạo giữ chỗ</button>}</div>
    {error&&<div className="suite-error-banner">{error}</div>}
    <section className="suite-panel"><div className="suite-table-wrap"><table className="suite-table"><thead><tr><th>Khách hàng</th><th>Mã mộ</th><th>Giai đoạn</th><th>Sale</th>{permissions.finance_view&&<><th>Giá trị</th><th>Hoa hồng</th></>}<th/></tr></thead><tbody>{deals.map(d=>{const removable=canRemoveDeal(d);return <tr key={d.id}><td><b>{d.lead_name||"—"}</b></td><td><b>{d.property_name?.replace(/^Mộ phần\s+/i,"")||"Chưa gắn mộ"}</b></td><td><span className="suite-status">{STAGE_LABEL[d.stage]||d.stage}</span></td><td>{d.owner_name||"—"}</td>{permissions.finance_view&&<><td>{money(d.value)}</td><td>{money(d.commission)}</td></>}<td>{permissions.deals_update&&<button className="suite-link" onClick={()=>openEdit(d)}>{isSale&&!['booking','cancelled'].includes(d.stage)?"Xem":"Sửa"}</button>} {permissions.deals_delete&&(removable?<button className="suite-link danger" onClick={()=>{setError("");setDeleteTarget(d)}}>Xóa</button>:<button className="suite-link" type="button" disabled title="Giao dịch đã qua cọc/hợp đồng/hoàn tất hoặc có chứng từ tài chính. Hãy chuyển sang Hủy để giữ lịch sử.">Không thể xóa</button>)}</td></tr>})}{!deals.length&&<tr><td colSpan="7"><div className="suite-empty">Chưa có giao dịch.</div></td></tr>}</tbody></table></div></section>
    {modal&&<div className="inventory-modal-overlay" onMouseDown={e=>e.target===e.currentTarget&&setModal(null)}><form className="inventory-modal cemetery-deal-modal" onSubmit={submit}><header><div><span className="eyebrow">{modal.mode==="add"?"TẠO GIỮ CHỖ":"CẬP NHẬT GIAO DỊCH"}</span><h2>{modal.mode==="add"?"Chọn khách và mã mộ":(modal.property_name||"Giao dịch")}</h2></div><button type="button" onClick={()=>setModal(null)}>×</button></header><div className="inventory-form-grid">
      {modal.mode==="add"&&<><label><span>Khách hàng</span><select required value={modal.lead_id} onChange={e=>setModal({...modal,lead_id:e.target.value})}><option value="">Chọn khách hàng</option>{(data.leads||[]).map(l=><option key={l.id} value={l.id}>{l.name} · {l.phone}</option>)}</select></label><label><span>Mã mộ phần</span><div className="cemetery-code-check"><input required value={modal.plot_code} onChange={e=>{setModal({...modal,plot_code:e.target.value});setPlot(null)}} placeholder="Ví dụ: C1-A-01-01"/><button type="button" className="suite-btn" onClick={checkPlot} disabled={checking}>{checking?"Đang kiểm tra":"Kiểm tra"}</button></div></label></>}
      <label><span>Giai đoạn</span><select disabled={saleLocked(modal)} value={modal.stage} onChange={e=>setModal({...modal,stage:e.target.value})}>{stageOptions().map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>{isSale&&<small>{saleLocked(modal)?"Giao dịch đã chuyển sang quy trình Tài chính; Sale chỉ được xem.":"Sale chỉ được Giữ chỗ hoặc Hủy giữ chỗ."}</small>}</label>
      {permissions.finance_view&&<><label><span>Giá trị giao dịch</span><input type="number" min="0" disabled={isSale} value={modal.value} onChange={e=>setModal({...modal,value:e.target.value})}/>{isSale&&<small>Giá lấy theo bảng giá mộ phần.</small>}</label><label><span>Hoa hồng dự kiến</span><input type="number" min="0" disabled={isSale} value={modal.commission} onChange={e=>setModal({...modal,commission:e.target.value})}/>{isSale&&<small>Hoa hồng do quy trình quản lý/Kế toán xử lý.</small>}</label></>}
      <label className="wide"><span>Ghi chú</span><textarea disabled={saleLocked(modal)} value={modal.notes} onChange={e=>setModal({...modal,notes:e.target.value})}/></label>
    </div>{plot&&<div className="cemetery-selected-plot"><div><span>Mã mộ</span><b>{plot.code}</b></div><div><span>Vị trí</span><b>{plot.cemetery_zone} / {plot.cemetery_subzone} / {plot.cemetery_row}</b></div><div><span>Loại</span><b>{plot.property_type} · {plot.grave_class}</b></div><div><span>Hướng</span><b>{plot.orientation||"—"}</b></div><div><span>Giá</span><b>{Number(plot.price_before_vat||0)>0?money(plot.price_before_vat):"Chưa có giá"}</b></div><div><span>Trạng thái</span><b>{PLOT_STATUS[plot.sales_status]||plot.source_status||"—"}</b></div></div>}{saleLocked(modal)&&<div className="finance-confirm-box"><b>Giao dịch đã qua Giữ chỗ</b><span>Cọc, hợp đồng, thanh toán và hoàn tất phải được xử lý trong module Hợp đồng & Tài chính để giữ đúng lịch sử chứng từ.</span></div>}<footer><button type="button" className="suite-btn" onClick={()=>setModal(null)}>{saleLocked(modal)?"Đóng":"Hủy"}</button>{!saleLocked(modal)&&<button className="suite-btn primary">{modal.mode==="add"?"Tạo giữ chỗ":"Lưu thay đổi"}</button>}</footer></form></div>}
    {deleteTarget&&<div className="inventory-modal-overlay" onMouseDown={e=>e.target===e.currentTarget&&setDeleteTarget(null)}><div className="inventory-modal cemetery-deal-modal"><header><div><span className="eyebrow">XÁC NHẬN</span><h2>Xóa giao dịch?</h2></div><button type="button" onClick={()=>setDeleteTarget(null)}>×</button></header><div className="finance-confirm-box"><b>{deleteTarget.lead_name||"Khách hàng"}</b><span>{deleteTarget.property_name||"Chưa gắn mộ"} · {STAGE_LABEL[deleteTarget.stage]||deleteTarget.stage}. Chỉ giao dịch giữ chỗ hoặc đã hủy, chưa phát sinh chứng từ tài chính mới được xóa.</span></div><footer><button type="button" className="suite-btn" onClick={()=>setDeleteTarget(null)}>Không xóa</button><button type="button" className="suite-btn primary" onClick={deleteDeal}>Xóa giao dịch</button></footer></div></div>}
  </div>
}