"use client";

import { compactMoney, money } from "@/lib/crm-client";

const VN_TZ="Asia/Ho_Chi_Minh";
const LEAD_STAGES=[["new","Khách mới"],["contact","Đã liên hệ"],["hot","Quan tâm"],["visit","Đi xem"],["deal","Chốt cọc"],["lost","Mất"]];
const OPPORTUNITY_STAGES=[["qualify","Đánh giá"],["consult","Tư vấn"],["visit","Đi xem"],["booking","Booking"],["deposit","Đặt cọc"],["contract","Hợp đồng"],["won","Thành công"],["lost","Thất bại"]];
function Metric({label,value,note,danger}){return <div className={`suite-metric ${danger?"dashboard-danger":""}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}
function vnDateKey(value=new Date()){const d=value instanceof Date?value:new Date(value);if(Number.isNaN(d.getTime()))return"";const p=Object.fromEntries(new Intl.DateTimeFormat("en-GB",{timeZone:VN_TZ,year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(d).map(({type,value})=>[type,value]));return `${p.year}-${p.month}-${p.day}`}
function vnDateTime(value){const d=new Date(value);if(Number.isNaN(d.getTime()))return"—";return new Intl.DateTimeFormat("vi-VN",{timeZone:VN_TZ,day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(d)}

export function ExecutiveDashboard({data,full,permissions,finance,financeReady}){
  const leads=data.leads||[],deals=data.deals||[],tasks=data.tasks||[],opportunities=full.opportunities||[],activities=full.activities||[],tickets=full.tickets||[],payments=finance?.payments||[];
  const openOpp=opportunities.filter(o=>o.status==="open"),pipeline=openOpp.reduce((s,o)=>s+Number(o.value||0),0),weighted=openOpp.reduce((s,o)=>s+Number(o.value||0)*Number(o.probability||0)/100,0);
  const wonOpp=opportunities.filter(o=>o.status==="won"),wonLeadIds=new Set(wonOpp.map(o=>o.lead_id).filter(Boolean)),conversion=leads.length?Math.min(100,Math.round(wonLeadIds.size/leads.length*100)):0,today=vnDateKey();
  const todayActivities=activities.filter(a=>vnDateKey(a.happened_at)===today).length,overdueTasks=tasks.filter(t=>!t.done&&t.due_at&&new Date(t.due_at)<new Date()).length;
  const urgentTickets=tickets.filter(t=>["open","processing"].includes(t.status)&&t.priority==="urgent").length;
  const overdueFollow=(full.lead_meta||[]).filter(m=>m.next_follow_up_at&&new Date(m.next_follow_up_at)<new Date()).length;
  const unassigned=leads.filter(l=>!l.owner_id).length,hotLeads=leads.filter(l=>["hot","visit"].includes(l.status)).length;
  const overduePayments=payments.filter(p=>p.status==="overdue").length;
  const activeBookings=deals.filter(d=>["booking","deposit","negotiation","contract"].includes(d.stage)).length;
  const fs=finance?.summary||{};
  return <div className="suite-page"><div className="suite-page-head"><div><h1>Trung tâm điều hành</h1><p>Toàn cảnh khách hàng, pipeline, chăm sóc, tài chính và rủi ro vận hành theo thời gian thực.</p></div><span className="suite-live">● Dữ liệu trực tiếp</span></div>
    <div className="suite-metric-grid"><Metric label="Khách hàng" value={leads.length} note={`${leads.filter(l=>l.status!=="lost").length} đang chăm sóc`}/><Metric label="Cơ hội đang mở" value={openOpp.length} note={permissions.finance_view?compactMoney(pipeline):"Giá trị ẩn theo quyền"}/><Metric label="Tỷ lệ chuyển đổi" value={`${conversion}%`} note={`${wonLeadIds.size} khách thắng · ${wonOpp.length} cơ hội thắng`}/><Metric label="Khách nóng" value={hotLeads} note={`${activeBookings} giao dịch đang chạy`}/><Metric label="Quá hạn chăm sóc" value={overdueFollow} note="Khách cần liên hệ ngay" danger={overdueFollow>0}/><Metric label="Chưa phân Sale" value={unassigned} note="Cần kiểm tra bộ chia lead" danger={unassigned>0}/><Metric label="Ticket khẩn" value={urgentTickets} note={`${tickets.filter(t=>!["resolved","closed"].includes(t.status)).length} ticket đang mở`} danger={urgentTickets>0}/><Metric label="Hoạt động hôm nay" value={todayActivities} note={`${overdueTasks} việc quá hạn`} danger={overdueTasks>0}/>{permissions.finance_view&&<Metric label="Pipeline trọng số" value={compactMoney(weighted)} note="Giá trị × xác suất"/>}{financeReady&&permissions.finance_view&&<Metric label="Công nợ phải thu" value={compactMoney(fs.receivable)} note={`${overduePayments} khoản quá hạn · ${compactMoney(fs.overdue)}`} danger={Number(fs.overdue)>0}/>}</div>
    <ActionCenter unassigned={unassigned} overdueFollow={overdueFollow} overdueTasks={overdueTasks} urgentTickets={urgentTickets} overduePayments={overduePayments} financeVisible={financeReady&&permissions.finance_view}/>
    <div className="suite-grid suite-grid-2 section-gap"><section className="suite-panel"><div className="suite-panel-head"><div><h2>Phễu khách hàng</h2><p>Tỷ trọng khách theo từng trạng thái</p></div></div><div className="suite-funnel">{LEAD_STAGES.map(([key,label])=>{const count=leads.filter(l=>l.status===key).length,width=leads.length?Math.max(5,Math.round(count/leads.length*100)):5;return <div className="suite-bar-row" key={key}><span>{label}</span><div><i style={{width:`${width}%`}}/></div><b>{count}</b></div>})}</div></section><section className="suite-panel"><div className="suite-panel-head"><div><h2>Pipeline cơ hội</h2><p>Số cơ hội theo giai đoạn bán hàng</p></div></div><div className="suite-funnel">{OPPORTUNITY_STAGES.map(([key,label])=>{const count=opportunities.filter(o=>o.stage===key).length,max=Math.max(1,...OPPORTUNITY_STAGES.map(([s])=>opportunities.filter(o=>o.stage===s).length));return <div className="suite-bar-row" key={key}><span>{label}</span><div><i style={{width:`${Math.max(5,Math.round(count/max*100))}%`}}/></div><b>{count}</b></div>})}</div></section></div>
    <div className="suite-grid suite-grid-2 section-gap"><SourcePerformance leads={leads} opportunities={opportunities}/><SalesLeaderboard data={data} leads={leads} opportunities={opportunities} deals={deals} permissions={permissions}/></div>
    <div className="suite-grid suite-grid-2 section-gap"><ActivityFeed rows={activities.slice(0,8)}/><RiskFeed leads={leads} full={full} tasks={tasks} tickets={tickets} payments={payments} permissions={permissions}/></div>
  </div>
}

function ActionCenter({unassigned,overdueFollow,overdueTasks,urgentTickets,overduePayments,financeVisible}){const rows=[{label:"Lead chưa phân Sale",value:unassigned,note:"Kiểm tra nhân sự đang điểm danh và vòng phân lead",danger:unassigned>0},{label:"Khách quá hạn chăm sóc",value:overdueFollow,note:"Ưu tiên gọi lại và đặt lịch tiếp theo",danger:overdueFollow>0},{label:"Công việc quá hạn",value:overdueTasks,note:"Rà soát deadline của Sales/CSKH",danger:overdueTasks>0},{label:"Ticket khẩn",value:urgentTickets,note:"Xử lý SLA khách hàng",danger:urgentTickets>0}];if(financeVisible)rows.push({label:"Khoản thu quá hạn",value:overduePayments,note:"Kế toán cần xử lý công nợ",danger:overduePayments>0});return <section className="suite-panel section-gap"><div className="suite-panel-head"><div><h2>Việc CEO cần chú ý</h2><p>Các điểm nghẽn đang ảnh hưởng trực tiếp tới tốc độ chốt và trải nghiệm khách hàng.</p></div></div><div className="suite-info-grid">{rows.map(r=><div key={r.label} className={r.danger?"dashboard-danger":""}><span>{r.label}</span><b>{r.value}</b><small>{r.note}</small></div>)}</div></section>}
function SourcePerformance({leads,opportunities}){const wonIds=new Set(opportunities.filter(o=>o.status==="won").map(o=>o.lead_id).filter(Boolean));const map=leads.reduce((a,l)=>{const k=l.source||"Khác";if(!a[k])a[k]={total:0,won:0};a[k].total++;if(wonIds.has(l.id))a[k].won++;return a},{}),rows=Object.entries(map).sort((a,b)=>b[1].total-a[1].total),max=Math.max(1,...rows.map(([,v])=>v.total));return <section className="suite-panel"><div className="suite-panel-head"><div><h2>Hiệu quả nguồn lead</h2><p>Khối lượng và chuyển đổi thành cơ hội thắng theo kênh</p></div></div><div className="suite-funnel">{rows.length?rows.map(([name,v])=><div className="suite-bar-row" key={name}><span>{name}<small>{v.total?` · ${Math.round(v.won/v.total*100)}% thắng`:""}</small></span><div><i style={{width:`${Math.round(v.total/max*100)}%`}}/></div><b>{v.total}</b></div>):<div className="suite-empty">Chưa có dữ liệu nguồn.</div>}</div></section>}
function SalesLeaderboard({data,leads,opportunities,deals,permissions}){const rows=(data.users||[]).filter(u=>u.role==="sale"&&u.active!==false).map(u=>{const saleLeads=leads.filter(l=>l.owner_id===u.id),saleOpp=opportunities.filter(o=>o.owner_id===u.id),won=saleOpp.filter(o=>o.status==="won"),wonLeadCount=new Set(won.map(o=>o.lead_id).filter(Boolean)).size,saleDeals=deals.filter(d=>d.owner_id===u.id&&d.stage!=="cancelled");return{id:u.id,name:u.name,leads:saleLeads.length,hot:saleLeads.filter(l=>["hot","visit","deal"].includes(l.status)).length,won:won.length,deals:saleDeals.length,value:saleDeals.reduce((s,d)=>s+Number(d.value||0),0),rate:saleLeads.length?Math.min(100,Math.round(wonLeadCount/saleLeads.length*100)):0}}).sort((a,b)=>b.won-a.won||b.deals-a.deals||b.hot-a.hot);return <section className="suite-panel"><div className="suite-panel-head"><div><h2>Bảng hiệu suất Sales</h2><p>Lead → khách nóng → giao dịch → thành công</p></div></div><div className="suite-table-wrap"><table className="suite-table"><thead><tr><th>Sale</th><th>Lead</th><th>Nóng</th><th>GD</th><th>Thắng</th><th>Tỷ lệ</th>{permissions.finance_view&&<th>Giá trị GD</th>}</tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.name}</b></td><td>{r.leads}</td><td>{r.hot}</td><td>{r.deals}</td><td>{r.won}</td><td>{r.rate}%</td>{permissions.finance_view&&<td>{compactMoney(r.value)}</td>}</tr>)}{!rows.length&&<tr><td colSpan="7"><div className="suite-empty">Chưa có nhân viên Sales hoạt động.</div></td></tr>}</tbody></table></div></section>}
function ActivityFeed({rows}){const type={call:"☎",meeting:"◫",message:"✉",email:"@",note:"✎",site_visit:"⌂",status_change:"↻",other:"•"};return <section className="suite-panel"><div className="suite-panel-head"><div><h2>Dòng hoạt động</h2><p>Tương tác khách hàng mới nhất</p></div></div><div className="suite-feed">{rows.length?rows.map(a=><div key={a.id} className="suite-feed-item"><span>{type[a.activity_type]||"•"}</span><div><b>{a.lead_name||"Khách hàng"}</b><p>{a.subject||a.content||a.activity_type}</p><small>{a.user_name||"Hệ thống"} · {vnDateTime(a.happened_at)}</small></div></div>):<div className="suite-empty">Chưa có lịch sử tương tác.</div>}</div></section>}
function RiskFeed({leads,full,tasks,tickets,payments,permissions}){const meta=new Map((full.lead_meta||[]).map(m=>[m.id,m]));const rows=[];for(const l of leads){const m=meta.get(l.id);if(m?.next_follow_up_at&&new Date(m.next_follow_up_at)<new Date())rows.push({key:`f-${l.id}`,title:l.name,note:`Quá hạn chăm sóc · ${l.owner_name||"Chưa giao Sale"}`})}for(const t of tasks.filter(t=>!t.done&&t.due_at&&new Date(t.due_at)<new Date()).slice(0,5))rows.push({key:`t-${t.id}`,title:t.title,note:`Công việc quá hạn · ${t.owner_name||"—"}`});for(const t of tickets.filter(t=>["open","processing"].includes(t.status)&&t.priority==="urgent").slice(0,5))rows.push({key:`k-${t.id}`,title:t.subject,note:`Ticket khẩn · ${t.assigned_name||"—"}`});if(permissions.finance_view)for(const p of payments.filter(p=>p.status==="overdue").slice(0,5))rows.push({key:`p-${p.id}`,title:p.lead_name||p.contract_code||"Khoản thu",note:`Công nợ quá hạn · ${compactMoney(p.amount)}`});return <section className="suite-panel"><div className="suite-panel-head"><div><h2>Danh sách rủi ro cần xử lý</h2><p>Ưu tiên từ chăm sóc khách đến SLA và công nợ.</p></div></div><div className="suite-feed">{rows.length?rows.slice(0,12).map(r=><div key={r.key} className="suite-feed-item"><span>!</span><div><b>{r.title}</b><p>{r.note}</p></div></div>):<div className="suite-empty">Hiện chưa có điểm nghẽn cần xử lý.</div>}</div></section>}

export function ReportsModule({data,full,permissions,finance,financeReady}){
  const leads=data.leads||[],opportunities=full.opportunities||[],campaigns=full.campaigns||[],deals=data.deals||[],activeDeals=deals.filter(d=>d.stage!=="cancelled"),fs=finance?.summary||{};
  const bySale=(data.users||[]).filter(u=>u.role==="sale").map(u=>{const saleLeads=leads.filter(l=>l.owner_id===u.id),saleOpp=opportunities.filter(o=>o.owner_id===u.id),wonOpp=saleOpp.filter(o=>o.status==="won"),wonLeadCount=new Set(wonOpp.map(o=>o.lead_id).filter(Boolean)).size;return{id:u.id,name:u.name,leads:saleLeads.length,open:saleOpp.filter(o=>o.status==="open").length,won:wonOpp.length,wonLeadCount,value:wonOpp.reduce((s,o)=>s+Number(o.value||0),0)}});
  const sourceRows=Object.entries(leads.reduce((a,l)=>{const k=l.source||"Khác";if(!a[k])a[k]={leads:0,won:0};a[k].leads++;if(opportunities.some(o=>o.lead_id===l.id&&o.status==="won"))a[k].won++;return a},{})).sort((a,b)=>b[1].leads-a[1].leads);
  return <div className="suite-page"><div className="suite-page-head"><div><h1>Báo cáo quản trị</h1><p>Báo cáo Sales, Marketing, CSKH và tài chính trên cùng một nguồn dữ liệu.</p></div></div><div className="suite-grid suite-grid-3"><section className="suite-panel"><h2>Khách hàng</h2><strong className="suite-big-number">{leads.length}</strong><p>{leads.filter(l=>l.status==="deal").length} khách đã chốt cọc</p></section><section className="suite-panel"><h2>Marketing</h2><strong className="suite-big-number">{campaigns.length}</strong><p>{campaigns.filter(c=>c.status==="active").length} chiến dịch đang chạy</p></section><section className="suite-panel"><h2>Giao dịch</h2><strong className="suite-big-number">{activeDeals.length}</strong><p>{permissions.finance_view?money(activeDeals.reduce((s,d)=>s+Number(d.value||0),0)):"Giá trị ẩn theo quyền"}</p></section></div>
    {financeReady&&permissions.finance_view&&<div className="suite-grid suite-grid-3 section-gap"><section className="suite-panel"><h2>Giá trị hợp đồng</h2><strong className="suite-big-number">{compactMoney(fs.contract_value)}</strong><p>Tổng hợp đồng chưa hủy</p></section><section className="suite-panel"><h2>Công nợ phải thu</h2><strong className="suite-big-number">{compactMoney(fs.receivable)}</strong><p>Các khoản đến hạn/chưa thu</p></section><section className="suite-panel"><h2>Quá hạn</h2><strong className="suite-big-number danger">{compactMoney(fs.overdue)}</strong><p>Cần Kế toán xử lý</p></section></div>}
    <section className="suite-panel section-gap"><div className="suite-panel-head"><div><h2>Hiệu suất Sales</h2><p>Từ lead → cơ hội → thành công</p></div></div><div className="suite-table-wrap"><table className="suite-table"><thead><tr><th>Nhân viên</th><th>Lead</th><th>Cơ hội mở</th><th>Thành công</th><th>Tỷ lệ</th>{permissions.finance_view&&<th>Giá trị thắng</th>}</tr></thead><tbody>{bySale.map(r=><tr key={r.id}><td><b>{r.name}</b></td><td>{r.leads}</td><td>{r.open}</td><td>{r.won}</td><td>{r.leads?Math.min(100,Math.round(r.wonLeadCount/r.leads*100)):0}%</td>{permissions.finance_view&&<td>{money(r.value)}</td>}</tr>)}</tbody></table></div></section>
    <div className="suite-grid suite-grid-2 section-gap"><section className="suite-panel"><div className="suite-panel-head"><div><h2>Chuyển đổi theo nguồn</h2><p>So sánh chất lượng lead giữa các kênh.</p></div></div><div className="suite-table-wrap"><table className="suite-table"><thead><tr><th>Nguồn</th><th>Lead</th><th>Thắng</th><th>Tỷ lệ</th></tr></thead><tbody>{sourceRows.map(([name,r])=><tr key={name}><td><b>{name}</b></td><td>{r.leads}</td><td>{r.won}</td><td>{r.leads?Math.round(r.won/r.leads*100):0}%</td></tr>)}</tbody></table></div></section><section className="suite-panel"><div className="suite-panel-head"><div><h2>Hiệu quả chiến dịch</h2><p>Lead tham gia và tỷ lệ chuyển đổi</p></div></div><div className="suite-table-wrap"><table className="suite-table"><thead><tr><th>Chiến dịch</th><th>Kênh</th><th>Lead</th><th>Chuyển đổi</th><th>Tỷ lệ</th></tr></thead><tbody>{campaigns.map(c=><tr key={c.id}><td><b>{c.name}</b></td><td>{c.channel}</td><td>{c.member_count||0}</td><td>{c.converted_count||0}</td><td>{Number(c.member_count)?Math.round(Number(c.converted_count||0)/Number(c.member_count)*100):0}%</td></tr>)}</tbody></table></div></section></div>
  </div>
}
