"use client";

import { useMemo, useState } from "react";
import { money, fmtDate } from "@/lib/crm-client";

const PROJECT_STATUS={planning:"Chuẩn bị",launching:"Mở bán",selling:"Đang bán",completed:"Hoàn tất",paused:"Tạm dừng"};
const PROPERTY_STATUS={available:"Còn hàng",reserved:"Giữ chỗ",sold:"Đã bán",locked:"Khóa"};
const LEAD_STATUS={new:"Khách mới",contact:"Đã liên hệ",hot:"Quan tâm",visit:"Đi xem",deal:"Chốt cọc",lost:"Không nhu cầu"};
const EMPTY_PROJECT={id:"",name:"",developer:"",location:"",status:"selling",description:"",launch_date:"",handover_date:""};
const EMPTY_BUILDING={id:"",project_id:"",name:"",code:"",status:"active",floors_count:"",notes:""};
const EMPTY_PROPERTY={id:"",name:"",code:"",project_id:"",building_id:"",floor_no:"",unit_no:"",property_type:"Căn hộ",area:"",bedrooms:"",price:"",status:"available",orientation:"",view_name:"",legal_status:"",handover_date:"",notes:""};

function Modal({title,onClose,onSubmit,children}){return <div className="inventory-modal-overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><form className="inventory-modal" onSubmit={onSubmit}><header><div><span className="eyebrow">PTM INVENTORY</span><h2>{title}</h2></div><button type="button" onClick={onClose}>×</button></header>{children}<footer><button type="button" className="suite-btn" onClick={onClose}>Hủy</button><button className="suite-btn primary">Lưu</button></footer></form></div>}
function Field({label,wide,children}){return <label className={wide?"wide":""}><span>{label}</span>{children}</label>}
function normPhone(v=""){let s=String(v).replace(/\D/g,"");if(/^84\d{9}$/.test(s))s="0"+s.slice(2);return s}
function keyName(v=""){return String(v).trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/đ/g,"d").replace(/[^a-z0-9]/g,"")}
function pick(row,names){const keys=Object.keys(row);for(const n of names){const found=keys.find(k=>keyName(k)===keyName(n));if(found!==undefined)return row[found]}return ""}
function parseMoney(v){if(typeof v==="number")return v;const s=String(v||"").replace(/[^0-9.-]/g,"");return Number(s)||0}
function normalizeStatus(v){const s=keyName(v);const map={new:"new",khachmoi:"new",contact:"contact",dalienhe:"contact",hot:"hot",quantam:"hot",visit:"visit",dixem:"visit",deal:"deal",chotcoc:"deal",lost:"lost",khongnhucau:"lost"};return map[s]||"new"}

export function InventoryModule({data,inventory,inventoryReady,permissions,inventoryMutate}){
  const canManage=permissions.properties_manage;
  const [tab,setTab]=useState("properties");
  const [projectFilter,setProjectFilter]=useState("");
  const [buildingFilter,setBuildingFilter]=useState("");
  const [statusFilter,setStatusFilter]=useState("");
  const [query,setQuery]=useState("");
  const [modal,setModal]=useState(null);
  const projects=inventory.projects||[];
  const buildings=inventory.buildings||[];
  const sourceProperties=inventoryReady?(inventory.properties||[]):(data.properties||[]);
  const properties=useMemo(()=>sourceProperties.filter(p=>(!projectFilter||p.project_id===projectFilter)&&(!buildingFilter||p.building_id===buildingFilter)&&(!statusFilter||p.status===statusFilter)&&(!query||`${p.code} ${p.name} ${p.project_name||p.project||""} ${p.building_name||""} ${p.floor_no||""}`.toLowerCase().includes(query.toLowerCase()))),[sourceProperties,projectFilter,buildingFilter,statusFilter,query]);
  const filteredBuildings=projectFilter?buildings.filter(b=>b.project_id===projectFilter):buildings;

  function projectModal(p={}){setModal({type:"project",draft:{...EMPTY_PROJECT,...p}})}
  function buildingModal(b={}){setModal({type:"building",draft:{...EMPTY_BUILDING,...b,project_id:b.project_id||projectFilter||""}})}
  function propertyModal(p={}){setModal({type:"property",draft:{...EMPTY_PROPERTY,...p,project_id:p.project_id||projectFilter||"",building_id:p.building_id||""}})}
  async function saveProject(e){e.preventDefault();await inventoryMutate("project.save",modal.draft);setModal(null)}
  async function saveBuilding(e){e.preventDefault();await inventoryMutate("building.save",modal.draft);setModal(null)}
  async function saveProperty(e){e.preventDefault();await inventoryMutate("property.save",modal.draft);setModal(null)}

  if(!inventoryReady)return <div className="suite-page"><div className="suite-page-head"><div><h1>Dự án & giỏ hàng</h1><p>Kho sản phẩm cơ bản vẫn hoạt động. Cấu trúc Dự án → Tòa → Tầng → Căn đang chờ migration đợt 2.</p></div></div><LegacyProperties rows={data.properties||[]}/></div>;

  return <div className="suite-page">
    <div className="suite-page-head"><div><h1>Dự án & giỏ hàng</h1><p>Quản lý phân cấp dự án, tòa/tháp, tầng, căn và tình trạng tồn kho theo thời gian thực.</p></div><div className="suite-action-row">{canManage&&<button className="suite-btn" onClick={()=>projectModal()}>+ Dự án</button>}{canManage&&<button className="suite-btn" onClick={()=>buildingModal()}>+ Tòa/Tháp</button>}{canManage&&<button className="suite-btn primary" onClick={()=>propertyModal()}>+ Căn/Sản phẩm</button>}</div></div>
    <div className="inventory-summary"><div><span>Dự án</span><strong>{projects.length}</strong></div><div><span>Tòa/Tháp</span><strong>{buildings.length}</strong></div><div><span>Tổng sản phẩm</span><strong>{sourceProperties.length}</strong></div><div><span>Còn hàng</span><strong>{sourceProperties.filter(p=>p.status==="available").length}</strong></div><div><span>Giữ chỗ</span><strong>{sourceProperties.filter(p=>p.status==="reserved").length}</strong></div><div><span>Đã bán</span><strong>{sourceProperties.filter(p=>p.status==="sold").length}</strong></div></div>
    <div className="inventory-tabs"><button className={tab==="properties"?"active":""} onClick={()=>setTab("properties")}>Giỏ hàng</button><button className={tab==="projects"?"active":""} onClick={()=>setTab("projects")}>Cấu trúc dự án</button></div>
    {tab==="properties"&&<><div className="inventory-filters"><input placeholder="Tìm mã căn, tên, tầng..." value={query} onChange={e=>setQuery(e.target.value)}/><select value={projectFilter} onChange={e=>{setProjectFilter(e.target.value);setBuildingFilter("")}}><option value="">Tất cả dự án</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={buildingFilter} onChange={e=>setBuildingFilter(e.target.value)}><option value="">Tất cả tòa/tháp</option>{filteredBuildings.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">Tất cả trạng thái</option>{Object.entries(PROPERTY_STATUS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><section className="suite-panel"><div className="suite-table-wrap"><table className="suite-table"><thead><tr><th>Mã căn</th><th>Dự án</th><th>Tòa</th><th>Tầng/Căn</th><th>Loại</th><th>DT</th><th>Giá</th><th>Trạng thái</th><th>Hướng/View</th><th/></tr></thead><tbody>{properties.map(p=><tr key={p.id}><td><b>{p.code}</b><small>{p.name}</small></td><td>{p.project_name||p.project}</td><td>{p.building_name||"—"}</td><td>{p.floor_no||"—"} / {p.unit_no||"—"}</td><td>{p.property_type} · {p.bedrooms||0}PN</td><td>{Number(p.area||0)} m²</td><td>{money(p.price)}</td><td><span className={`suite-status status-${p.status}`}>{PROPERTY_STATUS[p.status]||p.status}</span></td><td>{p.orientation||"—"}<small>{p.view_name||""}</small></td><td>{canManage&&<button className="suite-link" onClick={()=>propertyModal(p)}>Sửa</button>}</td></tr>)}{!properties.length&&<tr><td colSpan="10"><div className="suite-empty">Không có sản phẩm phù hợp bộ lọc.</div></td></tr>}</tbody></table></div></section></>}
    {tab==="projects"&&<div className="inventory-project-grid">{projects.map(p=>{const bs=buildings.filter(b=>b.project_id===p.id);const ps=sourceProperties.filter(x=>x.project_id===p.id);return <section className="suite-panel" key={p.id}><header className="inventory-project-head"><div><span className={`suite-status status-${p.status}`}>{PROJECT_STATUS[p.status]||p.status}</span><h2>{p.name}</h2><p>{p.developer||"Chưa cập nhật CĐT"} · {p.location||"Chưa cập nhật vị trí"}</p></div>{canManage&&<button className="suite-link" onClick={()=>projectModal(p)}>Sửa dự án</button>}</header><div className="inventory-project-stats"><span><b>{bs.length}</b>Tòa/Tháp</span><span><b>{ps.length}</b>Sản phẩm</span><span><b>{ps.filter(x=>x.status==="available").length}</b>Còn hàng</span></div><div className="inventory-building-list">{bs.map(b=><button key={b.id} onClick={()=>{setProjectFilter(p.id);setBuildingFilter(b.id);setTab("properties")}}><b>{b.name}</b><span>{b.floors_count||0} tầng · {ps.filter(x=>x.building_id===b.id).length} căn</span>{canManage&&<em onClick={e=>{e.stopPropagation();buildingModal(b)}}>Sửa</em>}</button>)}{!bs.length&&<div className="suite-empty">Chưa có tòa/tháp.</div>}</div></section>})}</div>}
    {modal?.type==="project"&&<Modal title={modal.draft.id?"Sửa dự án":"Tạo dự án"} onClose={()=>setModal(null)} onSubmit={saveProject}><div className="inventory-form-grid"><Field label="Tên dự án"><input required value={modal.draft.name} onChange={e=>setModal({...modal,draft:{...modal.draft,name:e.target.value}})}/></Field><Field label="Chủ đầu tư"><input value={modal.draft.developer||""} onChange={e=>setModal({...modal,draft:{...modal.draft,developer:e.target.value}})}/></Field><Field label="Vị trí"><input value={modal.draft.location||""} onChange={e=>setModal({...modal,draft:{...modal.draft,location:e.target.value}})}/></Field><Field label="Trạng thái"><select value={modal.draft.status} onChange={e=>setModal({...modal,draft:{...modal.draft,status:e.target.value}})}>{Object.entries(PROJECT_STATUS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><Field label="Ngày mở bán"><input type="date" value={String(modal.draft.launch_date||"").slice(0,10)} onChange={e=>setModal({...modal,draft:{...modal.draft,launch_date:e.target.value}})}/></Field><Field label="Ngày bàn giao"><input type="date" value={String(modal.draft.handover_date||"").slice(0,10)} onChange={e=>setModal({...modal,draft:{...modal.draft,handover_date:e.target.value}})}/></Field><Field label="Mô tả" wide><textarea value={modal.draft.description||""} onChange={e=>setModal({...modal,draft:{...modal.draft,description:e.target.value}})}/></Field></div></Modal>}
    {modal?.type==="building"&&<Modal title={modal.draft.id?"Sửa tòa/tháp":"Tạo tòa/tháp"} onClose={()=>setModal(null)} onSubmit={saveBuilding}><div className="inventory-form-grid"><Field label="Dự án"><select required value={modal.draft.project_id} onChange={e=>setModal({...modal,draft:{...modal.draft,project_id:e.target.value}})}><option value="">Chọn dự án</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Tên tòa/tháp"><input required value={modal.draft.name} onChange={e=>setModal({...modal,draft:{...modal.draft,name:e.target.value}})}/></Field><Field label="Mã tòa"><input value={modal.draft.code||""} onChange={e=>setModal({...modal,draft:{...modal.draft,code:e.target.value}})}/></Field><Field label="Số tầng"><input type="number" min="0" value={modal.draft.floors_count||""} onChange={e=>setModal({...modal,draft:{...modal.draft,floors_count:e.target.value}})}/></Field><Field label="Ghi chú" wide><textarea value={modal.draft.notes||""} onChange={e=>setModal({...modal,draft:{...modal.draft,notes:e.target.value}})}/></Field></div></Modal>}
    {modal?.type==="property"&&<PropertyModal modal={modal} setModal={setModal} projects={projects} buildings={buildings} onSubmit={saveProperty}/>} 
  </div>;
}

function PropertyModal({modal,setModal,projects,buildings,onSubmit}){const d=modal.draft;const set=(k,v)=>setModal({...modal,draft:{...d,[k]:v}});const bs=buildings.filter(b=>b.project_id===d.project_id);return <Modal title={d.id?"Sửa sản phẩm":"Tạo căn/sản phẩm"} onClose={()=>setModal(null)} onSubmit={onSubmit}><div className="inventory-form-grid"><Field label="Dự án"><select required value={d.project_id} onChange={e=>{setModal({...modal,draft:{...d,project_id:e.target.value,building_id:""}})}}><option value="">Chọn dự án</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Tòa/Tháp"><select value={d.building_id} onChange={e=>set("building_id",e.target.value)}><option value="">Không gắn tòa</option>{bs.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></Field><Field label="Mã căn/sản phẩm"><input required value={d.code} onChange={e=>set("code",e.target.value)}/></Field><Field label="Tên sản phẩm"><input required value={d.name} onChange={e=>set("name",e.target.value)}/></Field><Field label="Tầng"><input value={d.floor_no||""} onChange={e=>set("floor_no",e.target.value)}/></Field><Field label="Số căn"><input value={d.unit_no||""} onChange={e=>set("unit_no",e.target.value)}/></Field><Field label="Loại"><input value={d.property_type} onChange={e=>set("property_type",e.target.value)}/></Field><Field label="Diện tích m²"><input type="number" min="0" step="0.01" value={d.area||""} onChange={e=>set("area",e.target.value)}/></Field><Field label="Phòng ngủ"><input type="number" min="0" value={d.bedrooms||""} onChange={e=>set("bedrooms",e.target.value)}/></Field><Field label="Giá bán"><input type="number" min="0" value={d.price||""} onChange={e=>set("price",e.target.value)}/></Field><Field label="Trạng thái"><select value={d.status} onChange={e=>set("status",e.target.value)}>{Object.entries(PROPERTY_STATUS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><Field label="Hướng"><input value={d.orientation||""} onChange={e=>set("orientation",e.target.value)}/></Field><Field label="View"><input value={d.view_name||""} onChange={e=>set("view_name",e.target.value)}/></Field><Field label="Pháp lý"><input value={d.legal_status||""} onChange={e=>set("legal_status",e.target.value)}/></Field><Field label="Bàn giao"><input type="date" value={String(d.handover_date||"").slice(0,10)} onChange={e=>set("handover_date",e.target.value)}/></Field><Field label="Ghi chú" wide><textarea value={d.notes||""} onChange={e=>set("notes",e.target.value)}/></Field></div></Modal>}
function LegacyProperties({rows}){return <section className="suite-panel"><div className="suite-table-wrap"><table className="suite-table"><thead><tr><th>Mã</th><th>Dự án</th><th>Sản phẩm</th><th>Loại</th><th>Diện tích</th><th>Giá</th><th>Trạng thái</th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td><b>{p.code}</b></td><td>{p.project}</td><td>{p.name}</td><td>{p.property_type}</td><td>{p.area} m²</td><td>{money(p.price)}</td><td>{PROPERTY_STATUS[p.status]||p.status}</td></tr>)}</tbody></table></div></section>}

export function ImportLeadsModule({data,inventory,inventoryReady,inventoryMutate,bulkImportLeads}){
  const allowed=["admin","ceo","manager","marketing"].includes(data.user.role);
  const [file,setFile]=useState(null),[rows,setRows]=useState([]),[errors,setErrors]=useState([]),[busy,setBusy]=useState(false),[progress,setProgress]=useState({done:0,total:0}),[result,setResult]=useState(null);
  const existingPhones=new Set((data.leads||[]).map(l=>normPhone(l.phone)).filter(Boolean));
  const existingEmails=new Set((data.leads||[]).map(l=>String(l.email||"").trim().toLowerCase()).filter(Boolean));
  async function readFile(f){setFile(f);setRows([]);setErrors([]);setResult(null);if(!f)return;try{const XLSX=await import("xlsx");const wb=XLSX.read(await f.arrayBuffer(),{type:"array"});const raw=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:""});const seenPhones=new Set(),seenEmails=new Set();const parsed=raw.map((r,i)=>{const row={row:i+2,name:String(pick(r,["Họ tên","Tên khách hàng","Name"])).trim(),phone:String(pick(r,["SĐT","Số điện thoại","Phone"])).trim(),email:String(pick(r,["Email"])).trim(),source:String(pick(r,["Nguồn","Nguồn khách","Source"])||"Khác").trim(),project:String(pick(r,["Dự án","Dự án quan tâm","Project"])).trim(),need:String(pick(r,["Nhu cầu","Need"])).trim(),budget:parseMoney(pick(r,["Ngân sách","Budget"])),status:normalizeStatus(pick(r,["Tình trạng","Trạng thái","Status"])),notes:String(pick(r,["Ghi chú","Notes"])).trim()};const p=normPhone(row.phone),em=row.email.toLowerCase();const issues=[];if(!row.name)issues.push("Thiếu họ tên");if(!p)issues.push("Thiếu SĐT");if(p&&(existingPhones.has(p)||seenPhones.has(p)))issues.push("Trùng SĐT");if(em&&(existingEmails.has(em)||seenEmails.has(em)))issues.push("Trùng email");if(p)seenPhones.add(p);if(em)seenEmails.add(em);return {...row,issues}});setRows(parsed);setErrors(parsed.filter(r=>r.issues.length))}catch(e){setErrors([{row:"—",issues:[`Không đọc được file: ${e.message}`]}])}}
  async function importNow(){if(!allowed||!rows.length)return;const valid=rows.filter(r=>!r.issues.length);if(!valid.length)return;setBusy(true);setResult(null);setProgress({done:0,total:valid.length});let batchId="";try{if(inventoryReady){const started=await inventoryMutate("import.start",{import_type:"leads",file_name:file?.name||"import.xlsx",total_rows:valid.length},false);batchId=started?.id||""}const out=await bulkImportLeads(valid,(done,total)=>setProgress({done,total}));setResult(out);if(inventoryReady&&batchId)await inventoryMutate("import.complete",{id:batchId,successful_rows:out.success,failed_rows:out.failed.length,summary:{failed:out.failed.slice(0,100)}},false)}finally{setBusy(false)}}
  if(!allowed)return <div className="suite-page"><div className="suite-panel suite-empty suite-empty-large">Chỉ Giám đốc/Admin/Marketing được nhập khách hàng hàng loạt.</div></div>;
  return <div className="suite-page"><div className="suite-page-head"><div><h1>Nhập khách hàng Excel/CSV</h1><p>Đọc sheet đầu tiên, kiểm tra trùng SĐT/email và chỉ nhập các dòng hợp lệ.</p></div></div><section className="suite-panel import-panel"><div className="import-drop"><input type="file" accept=".xlsx,.xls,.csv" onChange={e=>readFile(e.target.files?.[0])}/><b>Chọn file Excel hoặc CSV</b><span>Cột hỗ trợ: Họ tên, SĐT, Email, Nguồn, Dự án, Nhu cầu, Ngân sách, Tình trạng, Ghi chú.</span></div>{file&&<div className="import-summary"><span><b>{file.name}</b>File</span><span><b>{rows.length}</b>Dòng dữ liệu</span><span><b>{rows.filter(r=>!r.issues.length).length}</b>Hợp lệ</span><span className={errors.length?"danger":""}><b>{errors.length}</b>Cần kiểm tra</span></div>}{rows.length>0&&<><div className="suite-table-wrap import-preview"><table className="suite-table"><thead><tr><th>Dòng</th><th>Khách hàng</th><th>SĐT</th><th>Email</th><th>Nguồn</th><th>Dự án</th><th>Tình trạng</th><th>Kiểm tra</th></tr></thead><tbody>{rows.slice(0,100).map(r=><tr key={r.row}><td>{r.row}</td><td><b>{r.name||"—"}</b></td><td>{r.phone||"—"}</td><td>{r.email||"—"}</td><td>{r.source}</td><td>{r.project||"—"}</td><td>{LEAD_STATUS[r.status]}</td><td>{r.issues.length?<span className="import-error">{r.issues.join(", ")}</span>:<span className="import-ok">✓ Hợp lệ</span>}</td></tr>)}</tbody></table></div><div className="import-actions">{busy&&<div className="import-progress"><span style={{width:`${progress.total?Math.round(progress.done/progress.total*100):0}%`}}/><b>{progress.done}/{progress.total}</b></div>}<button className="suite-btn primary" disabled={busy||!rows.some(r=>!r.issues.length)} onClick={importNow}>{busy?"Đang nhập...":`Nhập ${rows.filter(r=>!r.issues.length).length} khách hợp lệ`}</button></div></>}{result&&<div className="import-result"><b>Đã nhập thành công {result.success} khách.</b>{result.failed.length>0&&<span>{result.failed.length} dòng thất bại khi ghi database: {result.failed.slice(0,5).map(x=>`dòng ${x.row}: ${x.error}`).join(" · ")}</span>}</div>}{inventoryReady&&(inventory.imports||[]).length>0&&<div className="import-history"><h3>Lịch sử nhập gần đây</h3>{(inventory.imports||[]).slice(0,10).map(i=><div key={i.id}><b>{i.file_name}</b><span>{i.successful_rows}/{i.total_rows} thành công</span><small>{fmtDate(i.created_at,true)}</small></div>)}</div>}</section></div>;
}
