"use client";

import { useMemo, useState } from "react";
import { fmtDate, money } from "@/lib/crm-client";

const CHANNELS=[["facebook","Facebook"],["google","Google"],["tiktok","TikTok"],["zalo","Zalo"],["website","Website"],["event","Sự kiện"],["referral","Giới thiệu"],["other","Khác"]];
const STATUSES=[["draft","Nháp"],["active","Đang chạy"],["paused","Tạm dừng"],["completed","Hoàn tất"],["cancelled","Hủy"]];
const EMPTY={id:"",name:"",channel:"facebook",status:"draft",budget:"",target_leads:"",start_date:"",end_date:"",utm_source:"facebook",utm_medium:"paid",utm_campaign:"",notes:""};

export function MarketingModule({data,full,fullMutate}){
  const campaigns=full.campaigns||[];
  const canManage=["admin","ceo","manager","marketing"].includes(data.user.role);
  const[status,setStatus]=useState("all"),[modal,setModal]=useState(null),[memberModal,setMemberModal]=useState(null),[error,setError]=useState("");
  const rows=useMemo(()=>campaigns.filter(c=>status==="all"||c.status===status),[campaigns,status]);
  function openCampaign(c={}){setError("");setModal({...EMPTY,...c,budget:c.budget??"",target_leads:c.target_leads??"",notes:c.notes||"",utm_campaign:c.utm_campaign||""})}
  async function submitCampaign(e){e.preventDefault();setError("");try{if(!modal.name.trim())throw new Error("Vui lòng nhập tên chiến dịch.");await fullMutate("campaign.save",{...modal,name:modal.name.trim(),campaign_type:"digital",budget:Number(modal.budget||0),target_leads:Number(modal.target_leads||0),utm_source:modal.utm_source||modal.channel,utm_medium:modal.utm_medium||"paid",utm_campaign:modal.utm_campaign||modal.name.toLowerCase().replaceAll(" ","-"),notes:modal.notes||""});setModal(null)}catch(e2){setError(e2?.message||"Không thể lưu chiến dịch.")}}
  async function submitMember(e){e.preventDefault();setError("");try{if(!memberModal.lead_id)throw new Error("Vui lòng chọn khách hàng.");const lead=(data.leads||[]).find(l=>l.id===memberModal.lead_id);await fullMutate("campaign.add_member",{campaign_id:memberModal.campaign.id,lead_id:memberModal.lead_id,member_status:memberModal.member_status||"new",source_detail:memberModal.source_detail||lead?.source||"CRM"});setMemberModal(null)}catch(e2){setError(e2?.message||"Không thể thêm khách vào chiến dịch.")}}
  return <div className="suite-page"><div className="suite-page-head"><div><h1>Marketing</h1><p>Chiến dịch, nguồn lead, UTM và tỷ lệ chuyển đổi Marketing → Sales.</p></div>{canManage&&<button className="suite-btn primary" onClick={()=>openCampaign()}>+ Chiến dịch</button>}</div>
    <div className="suite-toolbar"><select className="suite-input" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Tất cả trạng thái</option>{STATUSES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><span>{rows.length} chiến dịch</span></div>
    <div className="suite-campaign-grid">{rows.map(c=>{const rate=Number(c.member_count)?Math.round(Number(c.converted_count||0)/Number(c.member_count)*100):0;const progress=Number(c.target_leads)?Math.min(100,Math.round(Number(c.member_count||0)/Number(c.target_leads)*100)):0;return <article className="suite-campaign-card" key={c.id}><header><span className={`suite-status status-${c.status}`}>{STATUSES.find(([v])=>v===c.status)?.[1]||c.status}</span><b>{CHANNELS.find(([v])=>v===c.channel)?.[1]||c.channel}</b></header><h2>{c.name}</h2><p>{fmtDate(c.start_date)} → {fmtDate(c.end_date)}</p><div className="suite-campaign-metrics"><div><strong>{c.member_count||0}</strong><span>Lead</span></div><div><strong>{c.converted_count||0}</strong><span>Chuyển đổi</span></div><div><strong>{rate}%</strong><span>Tỷ lệ</span></div></div><div className="suite-progress"><i style={{width:`${progress}%`}}/></div><small>Mục tiêu {c.target_leads||0} lead · {c.budget!==null?money(c.budget):"Ngân sách ẩn"}</small>{canManage&&<footer><button onClick={()=>openCampaign(c)}>Sửa</button><button onClick={()=>{setError("");setMemberModal({campaign:c,lead_id:"",member_status:"new",source_detail:""})}}>+ Lead</button></footer>}</article>})}</div>
    {modal&&<div className="customer-modal-overlay" onMouseDown={e=>e.target===e.currentTarget&&setModal(null)}><section className="customer-modal"><header><div><span className="eyebrow">MARKETING CRM</span><h2>{modal.id?"Cập nhật chiến dịch":"Tạo chiến dịch mới"}</h2></div><button className="customer-modal-close" type="button" onClick={()=>setModal(null)}>×</button></header><form className="customer-form" onSubmit={submitCampaign}><div className="customer-form-grid"><label>Tên chiến dịch <span className="customer-required">*</span><input autoFocus required value={modal.name} onChange={e=>setModal({...modal,name:e.target.value})}/></label><label>Kênh<select value={modal.channel} onChange={e=>setModal({...modal,channel:e.target.value,utm_source:e.target.value})}>{CHANNELS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Trạng thái<select value={modal.status} onChange={e=>setModal({...modal,status:e.target.value})}>{STATUSES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Ngân sách (VND)<input type="number" min="0" value={modal.budget} onChange={e=>setModal({...modal,budget:e.target.value})}/></label><label>Mục tiêu lead<input type="number" min="0" value={modal.target_leads} onChange={e=>setModal({...modal,target_leads:e.target.value})}/></label><label>Ngày bắt đầu<input type="date" value={modal.start_date||""} onChange={e=>setModal({...modal,start_date:e.target.value})}/></label><label>Ngày kết thúc<input type="date" value={modal.end_date||""} onChange={e=>setModal({...modal,end_date:e.target.value})}/></label><label>UTM Source<input value={modal.utm_source||""} onChange={e=>setModal({...modal,utm_source:e.target.value})}/></label><label>UTM Medium<input value={modal.utm_medium||""} onChange={e=>setModal({...modal,utm_medium:e.target.value})}/></label><label>UTM Campaign<input value={modal.utm_campaign||""} onChange={e=>setModal({...modal,utm_campaign:e.target.value})} placeholder="Tự tạo từ tên nếu để trống"/></label><label className="customer-form-wide">Ghi chú<textarea value={modal.notes||""} onChange={e=>setModal({...modal,notes:e.target.value})}/></label></div>{error&&<div className="customer-form-error">{error}</div>}<div className="customer-form-actions"><button type="button" className="suite-btn" onClick={()=>setModal(null)}>Hủy</button><button className="suite-btn primary">Lưu chiến dịch</button></div></form></section></div>}
    {memberModal&&<div className="customer-modal-overlay" onMouseDown={e=>e.target===e.currentTarget&&setMemberModal(null)}><section className="customer-modal"><header><div><span className="eyebrow">THÊM KHÁCH VÀO CHIẾN DỊCH</span><h2>{memberModal.campaign.name}</h2></div><button className="customer-modal-close" type="button" onClick={()=>setMemberModal(null)}>×</button></header><form className="customer-form" onSubmit={submitMember}><div className="customer-form-grid"><label className="customer-form-wide">Khách hàng <span className="customer-required">*</span><select required value={memberModal.lead_id} onChange={e=>setMemberModal({...memberModal,lead_id:e.target.value})}><option value="">Chọn khách hàng</option>{(data.leads||[]).map(l=><option key={l.id} value={l.id}>{l.name} · {l.phone} · {l.source||"Không rõ nguồn"}</option>)}</select></label><label>Trạng thái thành viên<select value={memberModal.member_status} onChange={e=>setMemberModal({...memberModal,member_status:e.target.value})}><option value="new">Mới</option><option value="contacted">Đã liên hệ</option><option value="converted">Đã chuyển đổi</option><option value="lost">Không chuyển đổi</option></select></label><label>Nguồn chi tiết<input value={memberModal.source_detail} onChange={e=>setMemberModal({...memberModal,source_detail:e.target.value})} placeholder="Ví dụ: Form Facebook A"/></label></div>{error&&<div className="customer-form-error">{error}</div>}<div className="customer-form-actions"><button type="button" className="suite-btn" onClick={()=>setMemberModal(null)}>Hủy</button><button className="suite-btn primary">Thêm khách</button></div></form></section></div>}
  </div>
}
