"use client";

import { useMemo, useState } from "react";
import { compactMoney, fmtDate } from "@/lib/crm-client";
import { roleLabel, ROLE_OPTIONS } from "@/lib/rbac";

const VN_TZ="Asia/Ho_Chi_Minh";
const TASK_TYPES=[["call","Gọi điện"],["meeting","Cuộc hẹn"],["followup","Chăm sóc"],["admin","Nội bộ"]];
const PRIORITIES=[["low","Thấp"],["normal","Bình thường"],["high","Cao"],["urgent","Khẩn cấp"]];
const TICKET_STATUS=[["open","Mới"],["processing","Đang xử lý"],["waiting_customer","Chờ khách"],["resolved","Đã xử lý"],["closed","Đóng"]];
const TICKET_CATEGORIES=[["support","Hỗ trợ"],["complaint","Khiếu nại"],["payment","Thanh toán"],["product","Sản phẩm"],["other","Khác"]];
const KPI_METRICS={new_leads:"Lead mới",activities:"Lượt chăm sóc",meetings:"Cuộc hẹn",visits:"Đi xem dự án",opportunities:"Cơ hội tạo mới",won_opportunities:"Cơ hội thành công",revenue:"Doanh số",tasks_done:"Công việc hoàn tất"};

function vnParts(){return Object.fromEntries(new Intl.DateTimeFormat("en-GB",{timeZone:VN_TZ,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date()).map(({type,value})=>[type,value]))}
function vnDateTimeLocal(offsetMinutes=60){const d=new Date(Date.now()+offsetMinutes*60000);const p=Object.fromEntries(new Intl.DateTimeFormat("en-GB",{timeZone:VN_TZ,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(d).map(({type,value})=>[type,value]));return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}`}
function vnMonth(){const p=vnParts();return `${p.year}-${p.month}`}
function vnMonthStart(){return `${vnMonth()}-01`}
function toVietnamIso(value){if(!value)return "";if(/[zZ]|[+-]\d\d:\d\d$/.test(value))return value;return `${value.length===16?value+":00":value}+07:00`}
function toLocalInput(value){if(!value)return "";const d=new Date(value);if(Number.isNaN(d.getTime()))return String(value).slice(0,16);const parts=Object.fromEntries(new Intl.DateTimeFormat("en-GB",{timeZone:VN_TZ,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(d).map(({type,value})=>[type,value]));return `${parts.year}-${parts.month}-${parts.day}T${parts.hour}:${parts.minute}`}
function Dialog({title,eyebrow="PTM CRM",onClose,children}){return <div className="customer-modal-overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="customer-modal"><header><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div><button className="customer-modal-close" type="button" onClick={onClose}>×</button></header>{children}</section></div>}

export function TicketsModule({data,full,fullMutate}){
  const tickets=full.tickets||[];
  const canCreate=["admin","ceo","manager","sale","marketing"].includes(data.user.role);
  const[modal,setModal]=useState(null),[error,setError]=useState("");
  const activeUsers=(data.users||[]).filter(u=>u.active!==false);
  function open(t={}){if(!canCreate)return;setError("");setModal({id:t.id||"",lead_id:t.lead_id||"",subject:t.subject||"",category:t.category||"support",priority:t.priority||"normal",status:t.status||"open",description:t.description||"",resolution:t.resolution||"",sla_due_at:toLocalInput(t.sla_due_at),assigned_to:t.assigned_to||data.user.id})}
  async function submit(e){e.preventDefault();setError("");try{if(!modal.subject.trim())throw new Error("Vui lòng nhập tiêu đề ticket.");await fullMutate("ticket.save",{...modal,subject:modal.subject.trim(),sla_due_at:toVietnamIso(modal.sla_due_at)});setModal(null)}catch(e2){setError(e2?.message||"Không thể lưu ticket.")}}
  return <div className="suite-page"><div className="suite-page-head"><div><h1>Ticket chăm sóc khách hàng</h1><p>Ghi nhận khiếu nại, yêu cầu hỗ trợ và SLA để không bỏ sót khách sau bán.</p></div>{canCreate&&<button className="suite-btn primary" onClick={()=>open()}>+ Ticket</button>}</div><div className="suite-ticket-board">{TICKET_STATUS.map(([status,label])=><section className="suite-ticket-col" key={status}><header><b>{label}</b><span>{tickets.filter(t=>t.status===status).length}</span></header>{tickets.filter(t=>t.status===status).map(t=><article key={t.id} onClick={()=>open(t)}><div><b>{t.code}</b><span className={`suite-priority priority-${t.priority}`}>{PRIORITIES.find(([v])=>v===t.priority)?.[1]||t.priority}</span></div><h3>{t.subject}</h3><p>{t.lead_name||"Không gắn khách"}</p><small>Phụ trách: {t.assigned_name||"—"}</small><footer><span>SLA {fmtDate(t.sla_due_at,true)}</span></footer></article>)}</section>)}</div>
    {modal&&<Dialog title={modal.id?"Cập nhật ticket":"Tạo ticket mới"} eyebrow="CSKH · SLA" onClose={()=>setModal(null)}><form className="customer-form" onSubmit={submit}><div className="customer-form-grid"><label className="customer-form-wide">Tiêu đề <span className="customer-required">*</span><input autoFocus required value={modal.subject} onChange={e=>setModal({...modal,subject:e.target.value})}/></label><label>Khách hàng<select value={modal.lead_id} onChange={e=>setModal({...modal,lead_id:e.target.value})}><option value="">Không gắn khách</option>{(data.leads||[]).map(l=><option key={l.id} value={l.id}>{l.name} · {l.phone}</option>)}</select></label><label>Phụ trách<select value={modal.assigned_to} onChange={e=>setModal({...modal,assigned_to:e.target.value})}>{activeUsers.map(u=><option key={u.id} value={u.id}>{u.name} · {roleLabel(u.role)}</option>)}</select></label><label>Nhóm yêu cầu<select value={modal.category} onChange={e=>setModal({...modal,category:e.target.value})}>{TICKET_CATEGORIES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Mức độ<select value={modal.priority} onChange={e=>setModal({...modal,priority:e.target.value})}>{PRIORITIES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Trạng thái<select value={modal.status} onChange={e=>setModal({...modal,status:e.target.value})}>{TICKET_STATUS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Hạn SLA<input type="datetime-local" value={modal.sla_due_at} onChange={e=>setModal({...modal,sla_due_at:e.target.value})}/></label><label className="customer-form-wide">Mô tả<textarea value={modal.description} onChange={e=>setModal({...modal,description:e.target.value})} placeholder="Nội dung khách cần hỗ trợ..."/></label><label className="customer-form-wide">Hướng xử lý / kết quả<textarea value={modal.resolution} onChange={e=>setModal({...modal,resolution:e.target.value})}/></label></div>{error&&<div className="customer-form-error">{error}</div>}<div className="customer-form-actions"><button type="button" className="suite-btn" onClick={()=>setModal(null)}>Hủy</button><button className="suite-btn primary">Lưu ticket</button></div></form></Dialog>}
  </div>
}

export function TasksModule({data,coreMutate}){
  const tasks=data.tasks||[];
  const[modal,setModal]=useState(null),[deleteTarget,setDeleteTarget]=useState(null),[error,setError]=useState("");
  const canAssign=["admin","ceo","manager"].includes(data.user.role);
  const activeUsers=(data.users||[]).filter(u=>u.active!==false);
  function open(t={}){setError("");setModal({id:t.id||"",title:t.title||"",task_type:t.task_type||"followup",due_at:toLocalInput(t.due_at)||vnDateTimeLocal(),priority:t.priority||"normal",owner_id:t.owner_id||data.user.id,lead_id:t.lead_id||"",done:t.done||false})}
  async function submit(e){e.preventDefault();setError("");try{if(!modal.title.trim())throw new Error("Vui lòng nhập nội dung công việc.");await coreMutate("save_task",{...modal,title:modal.title.trim(),due_at:toVietnamIso(modal.due_at),owner_id:canAssign?modal.owner_id:data.user.id});setModal(null)}catch(e2){setError(e2?.message||"Không thể lưu công việc.")}}
  return <div className="suite-page"><div className="suite-page-head"><div><h1>Công việc</h1><p>Giao việc, deadline và tiến độ cá nhân/phòng ban.</p></div><button className="suite-btn primary" onClick={()=>open()}>+ Công việc</button></div><section className="suite-panel"><div className="suite-table-wrap"><table className="suite-table"><thead><tr><th>Hoàn tất</th><th>Công việc</th><th>Loại</th><th>Deadline</th><th>Ưu tiên</th><th>Phụ trách</th><th/></tr></thead><tbody>{tasks.map(t=><tr key={t.id}><td><button className={`suite-check ${t.done?"done":""}`} onClick={()=>coreMutate("toggle_task",{id:t.id})}>{t.done?"✓":""}</button></td><td><button className="suite-link" onClick={()=>open(t)}><b>{t.title}</b></button><small>{t.lead_name||""}</small></td><td>{TASK_TYPES.find(([v])=>v===t.task_type)?.[1]||t.task_type}</td><td>{fmtDate(t.due_at,true)}</td><td><span className={`suite-priority priority-${t.priority}`}>{PRIORITIES.find(([v])=>v===t.priority)?.[1]||t.priority}</span></td><td>{t.owner_name||"—"}</td><td><button className="suite-link danger" onClick={()=>setDeleteTarget(t)}>Xóa</button></td></tr>)}{!tasks.length&&<tr><td colSpan="7"><div className="suite-empty">Chưa có công việc.</div></td></tr>}</tbody></table></div></section>
    {modal&&<Dialog title={modal.id?"Cập nhật công việc":"Tạo công việc mới"} eyebrow="VẬN HÀNH" onClose={()=>setModal(null)}><form className="customer-form" onSubmit={submit}><div className="customer-form-grid"><label className="customer-form-wide">Nội dung công việc <span className="customer-required">*</span><input autoFocus required value={modal.title} onChange={e=>setModal({...modal,title:e.target.value})}/></label><label>Loại công việc<select value={modal.task_type} onChange={e=>setModal({...modal,task_type:e.target.value})}>{TASK_TYPES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Ưu tiên<select value={modal.priority} onChange={e=>setModal({...modal,priority:e.target.value})}>{PRIORITIES.slice(0,3).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Deadline<input type="datetime-local" required value={modal.due_at} onChange={e=>setModal({...modal,due_at:e.target.value})}/></label><label>Khách hàng<select value={modal.lead_id} onChange={e=>setModal({...modal,lead_id:e.target.value})}><option value="">Không gắn khách</option>{(data.leads||[]).map(l=><option key={l.id} value={l.id}>{l.name} · {l.phone}</option>)}</select></label>{canAssign&&<label className="customer-form-wide">Người phụ trách<select value={modal.owner_id} onChange={e=>setModal({...modal,owner_id:e.target.value})}>{activeUsers.map(u=><option key={u.id} value={u.id}>{u.name} · {roleLabel(u.role)}</option>)}</select></label>}</div>{error&&<div className="customer-form-error">{error}</div>}<div className="customer-form-actions"><button type="button" className="suite-btn" onClick={()=>setModal(null)}>Hủy</button><button className="suite-btn primary">Lưu công việc</button></div></form></Dialog>}
    {deleteTarget&&<Dialog title="Xóa công việc?" eyebrow="XÁC NHẬN" onClose={()=>setDeleteTarget(null)}><div className="customer-form"><p>Bạn đang xóa <b>{deleteTarget.title}</b>. Thao tác này không thể hoàn tác.</p><div className="customer-form-actions"><button type="button" className="suite-btn" onClick={()=>setDeleteTarget(null)}>Không xóa</button><button type="button" className="suite-btn primary" onClick={async()=>{await coreMutate("delete_task",{id:deleteTarget.id});setDeleteTarget(null)}}>Xóa công việc</button></div></div></Dialog>}
  </div>
}

export function CalendarModule({data,full}){
  const items=useMemo(()=>{const taskItems=(data.tasks||[]).filter(t=>t.due_at&&!t.done).map(t=>({id:`task-${t.id}`,at:t.due_at,type:"Công việc",title:t.title,person:t.lead_name||t.owner_name}));const followups=(full.lead_meta||[]).filter(m=>m.next_follow_up_at).map(m=>{const l=(data.leads||[]).find(x=>x.id===m.id);return{id:`follow-${m.id}`,at:m.next_follow_up_at,type:"Chăm sóc",title:l?.name||"Khách hàng",person:l?.phone}});const activityNext=(full.activities||[]).filter(a=>a.next_action_at).map(a=>({id:`activity-${a.id}`,at:a.next_action_at,type:"Hẹn tiếp",title:a.lead_name,person:a.subject}));return[...taskItems,...followups,...activityNext].filter(x=>new Date(x.at)>=new Date(Date.now()-86400000)).sort((a,b)=>new Date(a.at)-new Date(b.at)).slice(0,100)},[data.tasks,data.leads,full.lead_meta,full.activities]);
  const grouped=items.reduce((acc,item)=>{const day=new Intl.DateTimeFormat("vi-VN",{timeZone:VN_TZ,day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date(item.at));(acc[day]||=[]).push(item);return acc},{});
  return <div className="suite-page"><div className="suite-page-head"><div><h1>Lịch hẹn & chăm sóc</h1><p>Tổng hợp deadline, lịch chăm sóc và lịch hẹn khách hàng.</p></div></div><div className="suite-calendar">{Object.keys(grouped).length?Object.entries(grouped).map(([day,rows])=><section className="suite-panel" key={day}><div className="suite-calendar-day"><b>{day}</b><span>{rows.length} lịch</span></div>{rows.map(x=><div className="suite-calendar-item" key={x.id}><time>{new Intl.DateTimeFormat("vi-VN",{timeZone:VN_TZ,hour:"2-digit",minute:"2-digit"}).format(new Date(x.at))}</time><span className="suite-status">{x.type}</span><div><b>{x.title}</b><small>{x.person||""}</small></div></div>)}</section>):<div className="suite-panel suite-empty suite-empty-large">Chưa có lịch sắp tới.</div>}</div></div>
}

export function KpiModule({data,full,fullMutate}){
  const canSet=["admin","ceo","manager"].includes(data.user.role);
  const targets=full.kpis||[];
  const sales=(data.users||[]).filter(u=>u.role==="sale"&&u.active!==false);
  const users=sales.length?sales:[data.user];
  const[modal,setModal]=useState(null),[error,setError]=useState("");
  const monthKey=vnMonth(),month=vnMonthStart();
  function actual(userId,metric){if(metric==="new_leads")return(data.leads||[]).filter(l=>(!userId||l.owner_id===userId)&&String(l.created_at||"").startsWith(monthKey)).length;if(metric==="activities")return(full.activities||[]).filter(a=>(!userId||a.user_id===userId)&&String(a.happened_at||"").startsWith(monthKey)).length;if(metric==="meetings")return(full.activities||[]).filter(a=>(!userId||a.user_id===userId)&&a.activity_type==="meeting"&&String(a.happened_at||"").startsWith(monthKey)).length;if(metric==="visits")return(full.activities||[]).filter(a=>(!userId||a.user_id===userId)&&a.activity_type==="site_visit"&&String(a.happened_at||"").startsWith(monthKey)).length;if(metric==="opportunities")return(full.opportunities||[]).filter(o=>(!userId||o.owner_id===userId)&&String(o.created_at||"").startsWith(monthKey)).length;if(metric==="won_opportunities")return(full.opportunities||[]).filter(o=>(!userId||o.owner_id===userId)&&o.status==="won"&&String(o.updated_at||"").startsWith(monthKey)).length;if(metric==="revenue")return(data.deals||[]).filter(d=>(!userId||d.owner_id===userId)&&d.stage==="completed"&&String(d.deal_date||"").startsWith(monthKey)).reduce((s,d)=>s+Number(d.value||0),0);if(metric==="tasks_done")return(data.tasks||[]).filter(t=>(!userId||t.owner_id===userId)&&t.done).length;return 0}
  function open(user,target=null){setError("");setModal({user_id:user.id,period_month:target?.period_month||month,metric_key:target?.metric_key||"new_leads",target_value:target?.target_value??10,weight:target?.weight??1})}
  async function submit(e){e.preventDefault();setError("");try{await fullMutate("kpi.save",{...modal,target_value:Number(modal.target_value||0),weight:Number(modal.weight||1)});setModal(null)}catch(e2){setError(e2?.message||"Không thể lưu KPI.")}}
  return <div className="suite-page"><div className="suite-page-head"><div><h1>KPI realtime</h1><p>Mục tiêu cá nhân được đối chiếu tự động với hoạt động phát sinh trong CRM.</p></div>{canSet&&<button className="suite-btn primary" onClick={()=>open(users[0])}>+ Thiết lập KPI</button>}</div><div className="suite-kpi-grid">{users.map(u=>{const rows=targets.filter(k=>k.user_id===u.id&&String(k.period_month||"").startsWith(monthKey));return <section className="suite-panel" key={u.id}><div className="suite-panel-head"><div><h3>{u.name}</h3><p>{roleLabel(u.role)}</p></div>{canSet&&<button className="suite-link" onClick={()=>open(u)}>+ KPI</button>}</div>{rows.length?rows.map(k=>{const a=actual(u.id,k.metric_key),target=Number(k.target_value||0),pct=target>0?Math.min(100,Math.round(a/target*100)):0;return <button key={k.id||`${u.id}-${k.metric_key}`} className="suite-kpi-row" onClick={()=>canSet&&open(u,k)}><div><b>{KPI_METRICS[k.metric_key]||k.metric_key}</b><small>{k.metric_key==="revenue"?compactMoney(a):a} / {k.metric_key==="revenue"?compactMoney(target):target}</small></div><div className="suite-progress"><i style={{width:`${pct}%`}}/></div><strong>{pct}%</strong></button>}):<div className="suite-empty">Chưa đặt KPI tháng này.</div>}</section>})}</div>
    {modal&&<Dialog title="Thiết lập KPI" eyebrow="QUẢN TRỊ" onClose={()=>setModal(null)}><form className="customer-form" onSubmit={submit}><div className="customer-form-grid"><label>Nhân viên<select value={modal.user_id} onChange={e=>setModal({...modal,user_id:e.target.value})}>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label>Tháng<input type="month" value={String(modal.period_month).slice(0,7)} onChange={e=>setModal({...modal,period_month:`${e.target.value}-01`})}/></label><label>Chỉ số KPI<select value={modal.metric_key} onChange={e=>setModal({...modal,metric_key:e.target.value})}>{Object.entries(KPI_METRICS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Mục tiêu<input type="number" min="0" required value={modal.target_value} onChange={e=>setModal({...modal,target_value:e.target.value})}/></label><label>Trọng số<input type="number" min="0" step="0.1" value={modal.weight} onChange={e=>setModal({...modal,weight:e.target.value})}/></label></div>{error&&<div className="customer-form-error">{error}</div>}<div className="customer-form-actions"><button type="button" className="suite-btn" onClick={()=>setModal(null)}>Hủy</button><button className="suite-btn primary">Lưu KPI</button></div></form></Dialog>}
  </div>
}

export function TeamModule({data,permissions,coreMutate}){
  const users=data.users||[];
  const canManage=data.permissions?.users_manage===true||permissions?.users_manage===true||["admin","ceo","manager"].includes(data.user.role);
  const[modal,setModal]=useState(null),[error,setError]=useState("");
  function open(u={}){if(!canManage)return;setError("");setModal({id:u.id||"",name:u.name||"",email:u.email||"",role:u.role||"sale",password:""})}
  async function submit(e){e.preventDefault();setError("");try{if(!modal.id&&!modal.name.trim())throw new Error("Vui lòng nhập họ tên.");if(!modal.id&&!modal.email.trim())throw new Error("Vui lòng nhập email đăng nhập.");if(!modal.id&&!modal.password)throw new Error("Vui lòng nhập mật khẩu ban đầu.");await coreMutate("save_user",{...modal,name:modal.name.trim(),email:modal.email.trim()});setModal(null)}catch(e2){setError(e2?.message||"Không thể lưu nhân viên.")}}
  return <div className="suite-page"><div className="suite-page-head"><div><h1>Đội ngũ & phân quyền</h1><p>Quản lý tài khoản nhân viên và quyền theo vai trò.</p></div>{canManage&&<button className="suite-btn primary" onClick={()=>open()}>+ Nhân viên</button>}</div><section className="suite-panel"><div className="suite-table-wrap"><table className="suite-table"><thead><tr><th>Nhân viên</th><th>Email</th><th>Vai trò</th><th>Trạng thái</th><th/></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><b>{u.name}</b></td><td>{u.email||"—"}</td><td><span className={`role role-${u.role}`}>{roleLabel(u.role)}</span></td><td>{u.active===false?"Đã khóa":"Hoạt động"}</td><td>{canManage&&<><button className="suite-link" onClick={()=>open(u)}>Sửa</button> {u.id!==data.user.id&&<button className="suite-link danger" onClick={()=>coreMutate("toggle_user",{id:u.id})}>{u.active===false?"Mở khóa":"Khóa"}</button>}</>}</td></tr>)}</tbody></table></div></section>
    {modal&&<Dialog title={modal.id?"Cập nhật nhân viên":"Tạo tài khoản nhân viên"} eyebrow="ĐỘI NGŨ & PHÂN QUYỀN" onClose={()=>setModal(null)}><form className="customer-form" onSubmit={submit}><div className="customer-form-grid"><label>Họ tên <span className="customer-required">*</span><input autoFocus required={!modal.id} value={modal.name} onChange={e=>setModal({...modal,name:e.target.value})}/></label><label>Email đăng nhập <span className="customer-required">*</span><input type="email" required={!modal.id} value={modal.email} onChange={e=>setModal({...modal,email:e.target.value})}/></label><label>Vai trò<select value={modal.role} onChange={e=>setModal({...modal,role:e.target.value})}>{ROLE_OPTIONS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>{modal.id?"Mật khẩu mới":"Mật khẩu ban đầu"}{!modal.id&&<span className="customer-required"> *</span>}<input type="password" required={!modal.id} value={modal.password} onChange={e=>setModal({...modal,password:e.target.value})} placeholder={modal.id?"Để trống nếu không đổi":"Tối thiểu theo quy định hệ thống"}/></label></div>{error&&<div className="customer-form-error">{error}</div>}<div className="customer-form-actions"><button type="button" className="suite-btn" onClick={()=>setModal(null)}>Hủy</button><button className="suite-btn primary">Lưu nhân viên</button></div></form></Dialog>}
  </div>
}
