const KEY='ptm_realty_crm_v2';
const seed={
leads:[
{id:1,name:'Nguyễn Minh Anh',phone:'0903 112 233',source:'Facebook',need:'Căn hộ 2PN',budget:3200000000,status:'new',owner:'Hà',project:'The Global City',last:'Hôm nay'},
{id:2,name:'Trần Quốc Bảo',phone:'0918 620 540',source:'TikTok',need:'Nhà phố',budget:6800000000,status:'contact',owner:'Nam',project:'Vinhomes Grand Park',last:'Hôm qua'},
{id:3,name:'Lê Thảo Vy',phone:'0938 345 228',source:'Website',need:'Đầu tư căn hộ',budget:4500000000,status:'hot',owner:'Hà',project:'Lumière Boulevard',last:'2 ngày trước'},
{id:4,name:'Phạm Gia Hưng',phone:'0907 928 118',source:'Giới thiệu',need:'Căn hộ 3PN',budget:5200000000,status:'visit',owner:'Khoa',project:'Masteri Centre Point',last:'3 ngày trước'},
{id:5,name:'Đỗ Thu Trang',phone:'0982 411 889',source:'Zalo',need:'Đất nền',budget:2500000000,status:'deal',owner:'Nam',project:'Long Thành',last:'Hôm nay'},
{id:6,name:'Võ Hoàng Long',phone:'0909 761 355',source:'Facebook',need:'Shophouse',budget:9200000000,status:'lost',owner:'Khoa',project:'Vinhomes Grand Park',last:'5 ngày trước'}],
properties:[
{id:1,name:'The Global City - 2PN',code:'TGC-A2-1208',project:'The Global City',type:'Căn hộ',area:75,price:4800000000,status:'Đang bán',bed:2},
{id:2,name:'Masteri Centre Point - 3PN',code:'MCP-B1-2210',project:'Masteri Centre Point',type:'Căn hộ',area:98,price:6200000000,status:'Đang bán',bed:3},
{id:3,name:'Nhà phố Manhattan',code:'VGP-MH-088',project:'Vinhomes Grand Park',type:'Nhà phố',area:84,price:14500000000,status:'Giữ chỗ',bed:4},
{id:4,name:'Lumière Boulevard - 2PN',code:'LB-C2-1811',project:'Lumière Boulevard',type:'Căn hộ',area:72,price:5100000000,status:'Đang bán',bed:2},
{id:5,name:'Đất nền Long Thành',code:'LT-B12-09',project:'Long Thành',type:'Đất nền',area:100,price:2700000000,status:'Đang bán',bed:0}],
deals:[
{id:1,lead:'Đỗ Thu Trang',property:'Đất nền Long Thành',value:2700000000,commission:81000000,stage:'Đặt cọc',owner:'Nam',date:'05/09/2026'},
{id:2,lead:'Phạm Gia Hưng',property:'Masteri Centre Point - 3PN',value:6200000000,commission:186000000,stage:'Chờ ký HĐ',owner:'Khoa',date:'02/09/2026'},
{id:3,lead:'Lê Thảo Vy',property:'Lumière Boulevard - 2PN',value:5100000000,commission:153000000,stage:'Thương lượng',owner:'Hà',date:'31/08/2026'}],
tasks:[
{id:1,title:'Gọi lại Nguyễn Minh Anh',type:'Gọi điện',due:'08/09/2026 10:30',owner:'Hà',done:false},
{id:2,title:'Gửi bảng giá The Global City',type:'Zalo',due:'08/09/2026 11:00',owner:'Hà',done:false},
{id:3,title:'Dẫn khách xem Masteri Centre Point',type:'Lịch hẹn',due:'08/09/2026 14:00',owner:'Khoa',done:false},
{id:4,title:'Theo dõi booking Long Thành',type:'Chăm sóc',due:'09/09/2026 09:00',owner:'Nam',done:false}]};

let state=load(),view='dashboard';
const meta={dashboard:['Tổng quan','Theo dõi hoạt động kinh doanh bất động sản hôm nay.'],leads:['Khách hàng','Quản lý lead, nhu cầu, nguồn và lịch sử chăm sóc.'],pipeline:['Pipeline','Theo dõi cơ hội bán hàng theo từng giai đoạn.'],properties:['Sản phẩm BĐS','Quản lý giỏ hàng, mã căn, giá và trạng thái.'],deals:['Giao dịch','Theo dõi booking, đặt cọc, hợp đồng và hoa hồng.'],tasks:['Công việc','Quản lý lịch gọi, lịch hẹn và việc cần xử lý.'],reports:['Báo cáo','Xem hiệu suất kinh doanh và nguồn khách hàng.']};
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(seed)}catch{return structuredClone(seed)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function money(v){return new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0}).format(v||0)}
function short(v){return v>=1e9?(v/1e9).toFixed(v%1e9?1:0)+' tỷ':v>=1e6?Math.round(v/1e6)+' tr':money(v)}
function toast(t){const e=document.querySelector('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1600)}
function badge(s){const labels={new:'Khách mới',contact:'Đã liên hệ',hot:'Quan tâm',visit:'Đi xem',deal:'Chốt cọc',lost:'Không nhu cầu'};return `<span class="badge ${s}">${labels[s]||s}</span>`}
function go(v){view=v;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===v));render();document.querySelector('.sidebar').classList.remove('open')}

document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.view));
document.querySelector('#menuBtn').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');
document.querySelector('#quickAddBtn').onclick=()=>leadModal();
document.querySelector('#closeModal').onclick=closeModal;
document.querySelector('#modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')closeModal()};
document.querySelector('#exportBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='ptm-crm-data.json';a.click();toast('Đã xuất dữ liệu CRM')};
document.querySelector('#globalSearch').oninput=e=>{if(e.target.value.trim()){go('leads');document.querySelector('#leadSearch').value=e.target.value;filterLeads()}};

function render(){document.querySelector('#pageTitle').textContent=meta[view][0];document.querySelector('#pageSubtitle').textContent=meta[view][1];const f={dashboard,leads,pipeline,properties,deals,tasks,reports}[view]||dashboard;document.querySelector('#view').innerHTML=f();bind()}
function dashboard(){const active=state.leads.filter(x=>x.status!=='lost').length,pipelineValue=state.leads.filter(x=>['hot','visit','deal'].includes(x.status)).reduce((a,b)=>a+b.budget,0),commission=state.deals.reduce((a,b)=>a+b.commission,0),months=[38,52,61,49,78,66],m=Math.max(...months);return `<div class="grid cards-4">${metric('◎',active,'Khách đang chăm sóc','+12% tháng này')}${metric('＋',state.leads.length,'Tổng khách hàng','+'+state.leads.filter(x=>x.status==='new').length+' khách mới')}${metric('₫',short(pipelineValue),'Giá trị cơ hội','Pipeline')}${metric('↗',short(commission),'Tổng hoa hồng','Dự kiến')}</div><div class="section kpi-chart"><div class="card panel chart-box"><div class="section-head"><div><h2>Lead theo tháng</h2><p>6 tháng gần nhất</p></div></div><div class="bars">${months.map((n,i)=>`<div class="bar-col"><div class="bar" style="height:${n/m*100}%"></div><label>T${i+4}</label></div>`).join('')}</div></div><div class="card panel"><div class="section-head"><div><h2>Tỷ lệ chuyển đổi</h2><p>Phân bổ theo giai đoạn</p></div></div>${[['Khách mới','new',100],['Đã liên hệ','contact',82],['Quan tâm','hot',61],['Đi xem','visit',38],['Chốt cọc','deal',24]].map(([n,s,p])=>`<div class="progress-row"><span>${n}</span><div class="progress"><i style="width:${p}%"></i></div><b>${state.leads.filter(x=>x.status===s).length}</b></div>`).join('')}</div></div><div class="section report-grid"><div class="card panel"><div class="section-head"><div><h2>Khách cần chăm sóc</h2><p>Khách mới và khách đang quan tâm</p></div><button class="btn ghost" data-go="leads">Xem tất cả</button></div>${leadTable(state.leads.filter(x=>x.status!=='lost').slice(0,5),false)}</div><div class="card panel"><div class="section-head"><div><h2>Công việc</h2><p>${state.tasks.filter(x=>!x.done).length} việc chưa hoàn tất</p></div></div>${taskList(state.tasks.slice(0,5))}</div></div>`}
function metric(icon,value,label,delta){return `<div class="card metric"><div class="metric-top"><div class="icon">${icon}</div><span class="delta up">${delta}</span></div><div class="value">${value}</div><div class="label">${label}</div></div>`}
function leads(){return `<div class="card panel"><div class="toolbar"><input id="leadSearch" placeholder="Tìm tên, SĐT, dự án..."><select id="leadStatus"><option value="">Tất cả trạng thái</option>${[['new','Khách mới'],['contact','Đã liên hệ'],['hot','Quan tâm'],['visit','Đi xem'],['deal','Chốt cọc'],['lost','Không nhu cầu']].map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('')}</select><button class="btn primary" id="addLead">+ Thêm khách hàng</button></div><div id="leadTable">${leadTable(state.leads,true)}</div></div>`}
function leadTable(rows,actions){return `<div class="table-wrap"><table><thead><tr><th>Khách hàng</th><th>Nguồn</th><th>Nhu cầu</th><th>Dự án</th><th>Ngân sách</th><th>Trạng thái</th><th>Sale</th>${actions?'<th></th>':''}</tr></thead><tbody>${rows.map(x=>`<tr data-search="${esc([x.name,x.phone,x.project,x.source,x.need].join(' ').toLowerCase())}" data-status="${x.status}"><td><span class="link" data-edit-lead="${x.id}">${esc(x.name)}</span><br><span class="muted">${esc(x.phone)}</span></td><td>${esc(x.source)}</td><td>${esc(x.need)}</td><td>${esc(x.project)}</td><td class="money">${short(x.budget)}</td><td>${badge(x.status)}</td><td>${esc(x.owner)}</td>${actions?`<td class="actions"><button data-edit-lead="${x.id}">Sửa</button><button data-del-lead="${x.id}">Xóa</button></td>`:''}</tr>`).join('')}</tbody></table></div>`}
function filterLeads(){const q=(document.querySelector('#leadSearch')?.value||'').toLowerCase(),s=document.querySelector('#leadStatus')?.value||'';document.querySelectorAll('#leadTable tbody tr').forEach(r=>r.style.display=(!q||r.dataset.search.includes(q))&&(!s||r.dataset.status===s)?'':'none')}
function pipeline(){return `<div class="pipeline">${[['new','Khách mới'],['contact','Đã liên hệ'],['hot','Quan tâm'],['visit','Đi xem'],['deal','Chốt cọc']].map(([s,n])=>{const a=state.leads.filter(x=>x.status===s);return `<div class="pipe-col"><div class="pipe-head"><strong>${n}</strong><span class="count">${a.length}</span></div>${a.map(x=>`<div class="lead-card" data-edit-lead="${x.id}"><strong>${esc(x.name)}</strong><p>${esc(x.need)} · ${esc(x.project)}</p><div class="flex space"><span class="price">${short(x.budget)}</span><span class="badge">${esc(x.owner)}</span></div></div>`).join('')||'<div class="empty">Chưa có khách</div>'}</div>`}).join('')}</div>`}
function properties(){return `<div class="toolbar"><input id="propertySearch" placeholder="Tìm sản phẩm, mã căn, dự án..."><button class="btn primary" id="addProperty">+ Thêm sản phẩm</button></div><div class="property-grid" id="propertyGrid">${state.properties.map(x=>`<div class="card property-card" data-search="${esc([x.name,x.code,x.project,x.type].join(' ').toLowerCase())}"><div class="property-hero">⌂ <span class="badge" style="margin-left:auto">${esc(x.status)}</span></div><div class="property-body"><h3>${esc(x.name)}</h3><p>Mã: <b>${esc(x.code)}</b></p><p>${esc(x.type)} · ${x.area} m²${x.bed?' · '+x.bed+' PN':''}</p><div class="property-price">${money(x.price)}</div><div class="actions" style="margin-top:12px"><button data-edit-property="${x.id}">Sửa</button><button data-del-property="${x.id}">Xóa</button></div></div></div>`).join('')}</div>`}
function deals(){const value=state.deals.reduce((a,b)=>a+b.value,0),com=state.deals.reduce((a,b)=>a+b.commission,0);return `<div class="grid cards-3"><div class="card stat-mini"><span>Tổng giá trị giao dịch</span><strong>${short(value)}</strong></div><div class="card stat-mini"><span>Hoa hồng dự kiến</span><strong>${short(com)}</strong></div><div class="card stat-mini"><span>Số giao dịch</span><strong>${state.deals.length}</strong></div></div><div class="section card panel"><div class="toolbar"><button class="btn primary" id="addDeal">+ Thêm giao dịch</button></div><div class="table-wrap"><table><thead><tr><th>Khách hàng</th><th>Sản phẩm</th><th>Giá trị</th><th>Hoa hồng</th><th>Giai đoạn</th><th>Sale</th><th>Ngày</th><th></th></tr></thead><tbody>${state.deals.map(x=>`<tr><td><b>${esc(x.lead)}</b></td><td>${esc(x.property)}</td><td class="money">${money(x.value)}</td><td>${money(x.commission)}</td><td><span class="badge deal">${esc(x.stage)}</span></td><td>${esc(x.owner)}</td><td>${esc(x.date)}</td><td><button data-del-deal="${x.id}">Xóa</button></td></tr>`).join('')}</tbody></table></div></div>`}
function taskList(rows){return rows.map(t=>`<div class="task-item ${t.done?'done':''}"><input class="task-check" type="checkbox" data-task="${t.id}" ${t.done?'checked':''}><div><strong>${esc(t.title)}</strong><span>${esc(t.type)} · ${esc(t.due)} · ${esc(t.owner)}</span></div><button data-del-task="${t.id}">Xóa</button></div>`).join('')}
function tasks(){return `<div class="grid cards-3"><div class="card stat-mini"><span>Chưa hoàn tất</span><strong>${state.tasks.filter(x=>!x.done).length}</strong></div><div class="card stat-mini"><span>Đã hoàn tất</span><strong>${state.tasks.filter(x=>x.done).length}</strong></div><div class="card stat-mini"><span>Tổng công việc</span><strong>${state.tasks.length}</strong></div></div><div class="section card panel"><div class="toolbar"><button class="btn primary" id="addTask">+ Thêm công việc</button></div>${taskList(state.tasks)}</div>`}
function reports(){const sources={};state.leads.forEach(x=>sources[x.source]=(sources[x.source]||0)+1);const owners={};state.leads.forEach(x=>(owners[x.owner]??={leads:0,deals:0}).leads++);state.deals.forEach(x=>(owners[x.owner]??={leads:0,deals:0}).deals++);const max=Math.max(...Object.values(sources),1);return `<div class="report-grid"><div class="card panel"><div class="section-head"><div><h2>Nguồn khách hàng</h2><p>Hiệu quả kênh marketing</p></div></div>${Object.entries(sources).map(([k,v])=>`<div class="progress-row"><span>${esc(k)}</span><div class="progress"><i style="width:${v/max*100}%"></i></div><b>${v}</b></div>`).join('')}</div><div class="card panel"><div class="section-head"><div><h2>Hiệu suất sales</h2><p>Lead và giao dịch</p></div></div><table><thead><tr><th>Nhân viên</th><th>Lead</th><th>Giao dịch</th></tr></thead><tbody>${Object.entries(owners).map(([k,v])=>`<tr><td>${esc(k)}</td><td>${v.leads}</td><td><b>${v.deals}</b></td></tr>`).join('')}</tbody></table></div></div>`}

function bind(){document.querySelectorAll('[data-go]').forEach(e=>e.onclick=()=>go(e.dataset.go));document.querySelectorAll('[data-edit-lead]').forEach(e=>e.onclick=()=>leadModal(+e.dataset.editLead));document.querySelectorAll('[data-del-lead]').forEach(e=>e.onclick=()=>remove('leads',+e.dataset.delLead));document.querySelectorAll('[data-edit-property]').forEach(e=>e.onclick=()=>propertyModal(+e.dataset.editProperty));document.querySelectorAll('[data-del-property]').forEach(e=>e.onclick=()=>remove('properties',+e.dataset.delProperty));document.querySelectorAll('[data-del-deal]').forEach(e=>e.onclick=()=>remove('deals',+e.dataset.delDeal));document.querySelectorAll('[data-del-task]').forEach(e=>e.onclick=()=>remove('tasks',+e.dataset.delTask));document.querySelectorAll('[data-task]').forEach(e=>e.onchange=()=>{state.tasks.find(t=>t.id===+e.dataset.task).done=e.checked;save();render()});const ls=document.querySelector('#leadSearch'),lf=document.querySelector('#leadStatus');if(ls)ls.oninput=filterLeads;if(lf)lf.onchange=filterLeads;const ps=document.querySelector('#propertySearch');if(ps)ps.oninput=()=>{const q=ps.value.toLowerCase();document.querySelectorAll('#propertyGrid [data-search]').forEach(e=>e.style.display=!q||e.dataset.search.includes(q)?'':'none')};const a=document.querySelector('#addLead');if(a)a.onclick=()=>leadModal();const p=document.querySelector('#addProperty');if(p)p.onclick=()=>propertyModal();const d=document.querySelector('#addDeal');if(d)d.onclick=dealModal;const t=document.querySelector('#addTask');if(t)t.onclick=taskModal}
function remove(k,id){if(!confirm('Xóa dữ liệu này?'))return;state[k]=state[k].filter(x=>x.id!==id);save();render();toast('Đã xóa dữ liệu')}
function modal(title,desc,html,cb){document.querySelector('#modalTitle').textContent=title;document.querySelector('#modalDesc').textContent=desc;const f=document.querySelector('#modalForm');f.innerHTML=html;f.onsubmit=e=>{e.preventDefault();cb(Object.fromEntries(new FormData(f)));closeModal()};document.querySelector('#modalBackdrop').classList.remove('hidden')}
function closeModal(){document.querySelector('#modalBackdrop').classList.add('hidden')}
function options(a,current){return a.map(v=>`<option ${current===v?'selected':''}>${v}</option>`).join('')}
function leadModal(id){const x=id?state.leads.find(x=>x.id===id):null;modal(x?'Cập nhật khách hàng':'Thêm khách hàng','Lưu thông tin lead và nhu cầu mua bất động sản.',`<div class="field"><label>Họ tên</label><input name="name" required value="${esc(x?.name||'')}"></div><div class="field"><label>Số điện thoại</label><input name="phone" required value="${esc(x?.phone||'')}"></div><div class="field"><label>Nguồn khách</label><select name="source">${options(['Facebook','TikTok','Website','Zalo','Giới thiệu','Khác'],x?.source)}</select></div><div class="field"><label>Sale phụ trách</label><select name="owner">${options(['Hà','Nam','Khoa','Admin'],x?.owner)}</select></div><div class="field"><label>Nhu cầu</label><input name="need" value="${esc(x?.need||'')}"></div><div class="field"><label>Ngân sách</label><input type="number" name="budget" value="${x?.budget||0}"></div><div class="field"><label>Dự án</label><input name="project" value="${esc(x?.project||'')}"></div><div class="field"><label>Trạng thái</label><select name="status">${[['new','Khách mới'],['contact','Đã liên hệ'],['hot','Quan tâm'],['visit','Đi xem'],['deal','Chốt cọc'],['lost','Không nhu cầu']].map(([v,n])=>`<option value="${v}" ${x?.status===v?'selected':''}>${n}</option>`).join('')}</select></div>${actions()}`,d=>{const o={...x,...d,id:x?.id||Date.now(),budget:+d.budget,last:'Vừa cập nhật'};state.leads=x?state.leads.map(i=>i.id===x.id?o:i):[o,...state.leads];save();render();toast('Đã lưu khách hàng')})}
function propertyModal(id){const x=id?state.properties.find(x=>x.id===id):null;modal(x?'Cập nhật sản phẩm':'Thêm sản phẩm BĐS','Quản lý giỏ hàng bất động sản.',`<div class="field"><label>Tên sản phẩm</label><input name="name" required value="${esc(x?.name||'')}"></div><div class="field"><label>Mã căn</label><input name="code" required value="${esc(x?.code||'')}"></div><div class="field"><label>Dự án</label><input name="project" value="${esc(x?.project||'')}"></div><div class="field"><label>Loại</label><select name="type">${options(['Căn hộ','Nhà phố','Biệt thự','Shophouse','Đất nền'],x?.type)}</select></div><div class="field"><label>Diện tích m²</label><input type="number" name="area" value="${x?.area||0}"></div><div class="field"><label>Phòng ngủ</label><input type="number" name="bed" value="${x?.bed||0}"></div><div class="field"><label>Giá bán</label><input type="number" name="price" value="${x?.price||0}"></div><div class="field"><label>Trạng thái</label><select name="status">${options(['Đang bán','Giữ chỗ','Đã bán','Tạm khóa'],x?.status)}</select></div>${actions()}`,d=>{const o={...x,...d,id:x?.id||Date.now(),area:+d.area,bed:+d.bed,price:+d.price};state.properties=x?state.properties.map(i=>i.id===x.id?o:i):[o,...state.properties];save();render();toast('Đã lưu sản phẩm')})}
function dealModal(){modal('Thêm giao dịch','Tạo booking, đặt cọc hoặc giao dịch mới.',`<div class="field"><label>Khách hàng</label><select name="lead">${options(state.leads.map(x=>x.name))}</select></div><div class="field"><label>Sản phẩm</label><select name="property">${options(state.properties.map(x=>x.name))}</select></div><div class="field"><label>Giá trị</label><input type="number" name="value" required></div><div class="field"><label>Hoa hồng</label><input type="number" name="commission" required></div><div class="field"><label>Giai đoạn</label><select name="stage">${options(['Booking','Đặt cọc','Thương lượng','Chờ ký HĐ','Hoàn tất'])}</select></div><div class="field"><label>Sale</label><select name="owner">${options(['Hà','Nam','Khoa','Admin'])}</select></div><div class="field full"><label>Ngày</label><input name="date" value="08/09/2026"></div>${actions()}`,d=>{state.deals.unshift({...d,id:Date.now(),value:+d.value,commission:+d.commission});save();render();toast('Đã thêm giao dịch')})}
function taskModal(){modal('Thêm công việc','Tạo lịch gọi, lịch hẹn hoặc việc cần xử lý.',`<div class="field full"><label>Nội dung</label><input name="title" required></div><div class="field"><label>Loại</label><select name="type">${options(['Gọi điện','Zalo','Lịch hẹn','Chăm sóc','CRM'])}</select></div><div class="field"><label>Phụ trách</label><select name="owner">${options(['Hà','Nam','Khoa','Admin'])}</select></div><div class="field full"><label>Thời hạn</label><input name="due" required placeholder="08/09/2026 15:00"></div>${actions()}`,d=>{state.tasks.unshift({...d,id:Date.now(),done:false});save();render();toast('Đã thêm công việc')})}
function actions(){return `<div class="form-actions"><button type="button" class="btn ghost" onclick="closeModal()">Hủy</button><button class="btn primary">Lưu</button></div>`}
render();
